import { buildStrategyContract } from "./strategy_contract.mjs";

const commonVersionTriggers = Object.freeze([
  "PRIMARY_OR_REQUIRED_FAMILY_CHANGE",
  "FACTOR_FORMULA_OR_NORMALIZATION_CHANGE",
  "SETUP_ELIGIBILITY_CHANGE",
  "INTERACTION_DEFINITION_CHANGE",
  "HARD_INVALIDATION_CHANGE",
  "ENTRY_EXIT_ADD_REDUCE_SEMANTICS_CHANGE",
  "HOLDING_HORIZON_CHANGE",
  "REGIME_GATE_CHANGE",
  "NUMERIC_WEIGHT_FLOOR_CAP_CHANGE",
]);

export const SHORT_MOMENTUM_CONTRACT_V0_1 = buildStrategyContract({
  strategyId: "SHORT_MOMENTUM",
  strategyVersion: "V0.1-CONTRACT",
  ownerApprovalState: "OWNER_APPROVED",
  thesis:
    "Capture short-horizon continuation or reacceleration when structure, participation and market/sector context align before the move becomes late-stage.",
  primaryHorizonSessions: [1, 3, 5, 10],
  evidenceFamilies: [
    {
      family: "TECHNICAL_STRUCTURE",
      role: "PRIMARY",
      factorIds: ["TECH.TREND", "TECH.STRUCTURE", "TECH.PATTERN_LIFECYCLE"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: true,
      notes: "Basic daily structure is derivable now; richer pattern lifecycle and historical semantics still require PIT validation.",
    },
    {
      family: "PRICE_VOLUME",
      role: "PRIMARY",
      factorIds: ["PV.RELATIVE_VOLUME", "PV.ACCEPTANCE", "PV.RESPONSE"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: true,
      notes: "Daily volume/response is available; same-slot and cumulative intraday research remains evidence-gated.",
    },
    {
      family: "MARKET_REGIME",
      role: "PRIMARY",
      factorIds: ["REGIME.TAIEX", "REGIME.BREADTH", "REGIME.SECTOR_ROTATION"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: false,
      notes: "TAIEX is current-ready; TPEx/breadth/sector vintage coverage remains incomplete. Regime changes priority rather than universally blocking the strategy.",
    },
    {
      family: "CAPITAL_FLOW",
      role: "SUPPORTIVE",
      factorIds: ["FLOW.INSTITUTION", "FLOW.SECTOR"],
      dataReadiness: "READY_CURRENT",
      unknownBlocksEligibility: false,
    },
    {
      family: "RISK_FRICTION",
      role: "REQUIRED",
      factorIds: ["RISK.LIQUIDITY", "RISK.EXTENSION", "RISK.REWARD_RISK"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: true,
    },
    {
      family: "FUNDAMENTAL_QUALITY",
      role: "CONTEXT_ONLY",
      factorIds: ["FUND.MATERIAL_RISK"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: false,
    },
  ],
  setups: [
    {
      setupId: "BREAKOUT_CONTINUATION",
      setupVersion: "0.1",
      thesisMechanism: "Mature structure breaks and receives price-volume acceptance without excessive extension.",
      requiredFamilies: ["TECHNICAL_STRUCTURE", "PRICE_VOLUME", "RISK_FRICTION"],
      supportiveFamilies: ["MARKET_REGIME", "CAPITAL_FLOW"],
      contextFamilies: ["FUNDAMENTAL_QUALITY", "EVENT_CATALYST"],
      hardInvalidationIds: ["FAILED_BREAKOUT", "STRUCTURE_BREAK", "MATERIAL_ADVERSE_EVENT"],
      entryReadinessInputs: ["BREAKOUT_LIFECYCLE", "PV_ACCEPTANCE", "EXTENSION_STATE", "REWARD_RISK"],
      intradayRole: "HIGH",
      expectedHorizonSessions: [1, 3, 5, 10],
      addActionFamilies: ["ADD_ON_STRENGTH", "ADD_ON_PULLBACK"],
      reduceActionFamilies: ["CLIMAX_REDUCE", "PROFIT_PROTECT", "QUALITY_DETERIORATION_REDUCE"],
      exitActionFamilies: ["HARD_STOP", "STRUCTURE_STOP", "THESIS_EXIT", "TIME_EXIT", "TRAILING_EXIT"],
    },
    {
      setupId: "PULLBACK_REACCELERATION",
      setupVersion: "0.1",
      thesisMechanism: "Existing short-term uptrend pulls back constructively, then reaccelerates with renewed acceptance.",
      requiredFamilies: ["TECHNICAL_STRUCTURE", "PRICE_VOLUME", "RISK_FRICTION"],
      supportiveFamilies: ["MARKET_REGIME", "CAPITAL_FLOW"],
      contextFamilies: ["FUNDAMENTAL_QUALITY", "EVENT_CATALYST"],
      hardInvalidationIds: ["SUPPORT_FAILURE", "PRICE_REJECTION", "MATERIAL_ADVERSE_EVENT"],
      entryReadinessInputs: ["PULLBACK_STRUCTURE", "VOLUME_CONTRACTION", "REACCELERATION", "REWARD_RISK"],
      intradayRole: "HIGH",
      expectedHorizonSessions: [1, 3, 5, 10],
      addActionFamilies: ["ADD_ON_PULLBACK", "ADD_ON_STRENGTH"],
      reduceActionFamilies: ["CLIMAX_REDUCE", "PROFIT_PROTECT"],
      exitActionFamilies: ["HARD_STOP", "STRUCTURE_STOP", "THESIS_EXIT", "TIME_EXIT"],
    },
  ],
  allowedRegimes: ["RISK_ON", "TREND", "SECTOR_ROTATION", "RECOVERY", "RANGE"],
  blockedRegimes: [],
  hardInvalidationIds: ["FAILED_BREAKOUT", "BROKEN_ACTIVE_STRUCTURE", "SEVERE_ILLIQUIDITY", "MATERIAL_ADVERSE_EVENT"],
  interactionIds: ["BREAKOUT_ACCEPTANCE_CONFLUENCE"],
  versionChangeTriggers: commonVersionTriggers,
  notes: [
    "No universal Risk-off hard block is frozen.",
    "Technical patterns never act as sole entry/exit authority.",
    "No numeric weight or threshold is frozen.",
  ],
});

export const SWING_GROWTH_CONTRACT_V0_1 = buildStrategyContract({
  strategyId: "SWING_GROWTH",
  strategyVersion: "V0.1-CONTRACT",
  ownerApprovalState: "OWNER_APPROVED",
  thesis:
    "Capture market repricing of an improving future earnings path when the improvement mechanism is knowable, durable enough for the horizon and not already fully reflected.",
  primaryHorizonSessions: [10, 20, 40, 60],
  evidenceFamilies: [
    {
      family: "INDUSTRY_THESIS",
      role: "PRIMARY",
      factorIds: ["IND.CYCLE_STAGE", "IND.DEMAND_SUPPLY", "IND.COMPANY_TRANSMISSION"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: true,
      notes: "Prospective current context is usable; historical classification and industry-vintage controls remain required.",
    },
    {
      family: "FUNDAMENTAL_QUALITY",
      role: "PRIMARY",
      factorIds: ["FUND.GROWTH_ACCELERATION", "FUND.MARGIN_QUALITY", "FUND.EARNINGS_QUALITY"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: true,
      notes: "Quarterly financials are current-ready but historical publication-time semantics require audit.",
    },
    {
      family: "EVENT_CATALYST",
      role: "PRIMARY",
      factorIds: ["EVENT.CATALYST", "EVENT.EXPECTATION_CHANGE"],
      dataReadiness: "SEMANTIC_GAP",
      unknownBlocksEligibility: false,
      notes: "Official announcements are date-level today; precise expectation/surprise and intraday first-known data are not canonical.",
    },
    {
      family: "VALUATION",
      role: "REQUIRED",
      factorIds: ["VAL.PE", "VAL.PB", "VAL.REWARD_RISK"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: false,
      notes: "Current PE/PB exists; forward PE/PEG/history percentiles are not canonical.",
    },
    {
      family: "TECHNICAL_STRUCTURE",
      role: "SUPPORTIVE",
      factorIds: ["TECH.BASE", "TECH.PULLBACK", "TECH.EXTENSION"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: false,
    },
    {
      family: "PRICE_VOLUME",
      role: "SUPPORTIVE",
      factorIds: ["PV.ACCEPTANCE", "PV.PULLBACK_QUALITY"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: false,
    },
    {
      family: "CHIP_OWNERSHIP",
      role: "SUPPORTIVE",
      factorIds: ["CHIP.TDCC_CONCENTRATION", "FLOW.INSTITUTION"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: false,
    },
  ],
  setups: [
    {
      setupId: "GROWTH_BREAKOUT",
      setupVersion: "0.1",
      thesisMechanism: "PIT-valid earnings/industry improvement is followed by a technically acceptable repricing breakout.",
      requiredFamilies: ["INDUSTRY_THESIS", "FUNDAMENTAL_QUALITY"],
      supportiveFamilies: ["EVENT_CATALYST", "TECHNICAL_STRUCTURE", "PRICE_VOLUME", "CHIP_OWNERSHIP"],
      contextFamilies: ["VALUATION", "MARKET_REGIME"],
      hardInvalidationIds: ["GROWTH_PATH_FAILURE", "CATALYST_FAILURE", "CYCLE_REVERSAL"],
      entryReadinessInputs: ["FUNDAMENTAL_INFLECTION", "VALUATION_CONTEXT", "BASE_BREAKOUT", "PV_ACCEPTANCE"],
      intradayRole: "MEDIUM",
      expectedHorizonSessions: [10, 20, 40, 60],
      addActionFamilies: ["ADD_ON_NEW_INFORMATION", "ADD_ON_STRENGTH", "ADD_ON_PULLBACK"],
      reduceActionFamilies: ["GROWTH_DECELERATION_REDUCE", "VALUATION_OVERRUN_REDUCE", "MARGIN_DETERIORATION_REDUCE"],
      exitActionFamilies: ["THESIS_EXIT", "STRUCTURE_EXIT", "TIME_EXIT"],
    },
    {
      setupId: "GROWTH_PULLBACK",
      setupVersion: "0.1",
      thesisMechanism: "The growth/repricing thesis remains intact while price resets toward a better reward-risk zone.",
      requiredFamilies: ["INDUSTRY_THESIS", "FUNDAMENTAL_QUALITY"],
      supportiveFamilies: ["TECHNICAL_STRUCTURE", "PRICE_VOLUME", "CHIP_OWNERSHIP"],
      contextFamilies: ["VALUATION", "MARKET_REGIME", "EVENT_CATALYST"],
      hardInvalidationIds: ["GROWTH_PATH_FAILURE", "CYCLE_REVERSAL", "MAJOR_CUSTOMER_PRODUCT_FAILURE"],
      entryReadinessInputs: ["THESIS_VALIDITY", "PULLBACK_QUALITY", "EXTENSION_RESET", "REWARD_RISK"],
      intradayRole: "MEDIUM",
      expectedHorizonSessions: [10, 20, 40, 60],
      addActionFamilies: ["ADD_ON_PULLBACK", "ADD_ON_NEW_INFORMATION"],
      reduceActionFamilies: ["THESIS_WEAKENING_REDUCE", "VALUATION_OVERRUN_REDUCE"],
      exitActionFamilies: ["THESIS_EXIT", "STRUCTURE_EXIT"],
    },
    {
      setupId: "EARLY_GROWTH_INFLECTION",
      setupVersion: "0.1",
      thesisMechanism: "Growth moves from deceleration toward acceleration before headline financial metrics become obviously strong.",
      requiredFamilies: ["INDUSTRY_THESIS", "FUNDAMENTAL_QUALITY"],
      supportiveFamilies: ["EVENT_CATALYST", "CHIP_OWNERSHIP", "TECHNICAL_STRUCTURE", "PRICE_VOLUME"],
      contextFamilies: ["VALUATION", "MARKET_REGIME"],
      hardInvalidationIds: ["INFLECTION_FALSIFIED", "CYCLE_REVERSAL", "PIT_SOURCE_FAILURE"],
      entryReadinessInputs: ["GROWTH_ACCELERATION", "MARGIN_OR_CASHFLOW_SUPPORT", "TIMING_STRUCTURE", "REWARD_RISK"],
      intradayRole: "LOW",
      expectedHorizonSessions: [20, 40, 60],
      addActionFamilies: ["ADD_ON_NEW_INFORMATION", "ADD_ON_STRENGTH"],
      reduceActionFamilies: ["INFLECTION_WEAKENING_REDUCE"],
      exitActionFamilies: ["THESIS_EXIT", "TIME_EXIT"],
    },
  ],
  allowedRegimes: ["RISK_ON", "TREND", "SECTOR_ROTATION", "RECOVERY", "RANGE", "RISK_OFF"],
  blockedRegimes: [],
  hardInvalidationIds: ["GROWTH_PATH_FAILURE", "CYCLE_REVERSAL", "MAJOR_CUSTOMER_PRODUCT_FAILURE", "PIT_SOURCE_FAILURE"],
  interactionIds: ["GROWTH_REPRICING_CONFLUENCE"],
  versionChangeTriggers: commonVersionTriggers,
  notes: [
    "Short-term oscillators cannot prove future growth.",
    "Cyclical-peak traps require explicit counterevidence checks.",
    "No numeric weight or threshold is frozen.",
  ],
});

export const INDUSTRY_TREND_CONTRACT_V0_1 = buildStrategyContract({
  strategyId: "INDUSTRY_TREND",
  strategyVersion: "V0.1-CONTRACT",
  ownerApprovalState: "OWNER_APPROVED",
  thesis:
    "Capture persistent industry-cycle or structural supply-demand improvement when a company has a clear earnings-transmission path and the benefit is not fully priced.",
  primaryHorizonSessions: [20, 40, 60, 120],
  evidenceFamilies: [
    {
      family: "INDUSTRY_THESIS",
      role: "PRIMARY",
      factorIds: ["IND.CYCLE_STAGE", "IND.SUPPLY_DEMAND", "IND.INVENTORY", "IND.CAPACITY", "IND.PRICING", "IND.COMPANY_TRANSMISSION"],
      dataReadiness: "SOURCE_EXTENSION_REQUIRED",
      unknownBlocksEligibility: true,
      notes: "Generic sector context is prospectively derivable, but many industry-specific supply/demand/inventory/capacity series still lack canonical contracts.",
    },
    {
      family: "FUNDAMENTAL_QUALITY",
      role: "SUPPORTIVE",
      factorIds: ["FUND.EARNINGS_SENSITIVITY", "FUND.MARGIN_QUALITY"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: false,
    },
    {
      family: "VALUATION",
      role: "SUPPORTIVE",
      factorIds: ["VAL.PE", "VAL.PB", "VAL.CYCLE_CONTEXT"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: false,
    },
    {
      family: "CAPITAL_FLOW",
      role: "SUPPORTIVE",
      factorIds: ["FLOW.INSTITUTION", "FLOW.SECTOR"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: false,
    },
    {
      family: "TECHNICAL_STRUCTURE",
      role: "SUPPORTIVE",
      factorIds: ["TECH.CYCLE_BASE", "TECH.TREND_PULLBACK", "TECH.SECOND_LEG"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: false,
    },
    {
      family: "PRICE_VOLUME",
      role: "SUPPORTIVE",
      factorIds: ["PV.ACCEPTANCE", "PV.PULLBACK_QUALITY"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: false,
    },
  ],
  setups: [
    {
      setupId: "EARLY_CYCLE_ENTRY",
      setupVersion: "0.1",
      thesisMechanism: "Industry cycle improves from an early stage and company-level earnings transmission is credible before full price repricing.",
      requiredFamilies: ["INDUSTRY_THESIS"],
      supportiveFamilies: ["FUNDAMENTAL_QUALITY", "VALUATION", "CAPITAL_FLOW", "TECHNICAL_STRUCTURE", "PRICE_VOLUME"],
      contextFamilies: ["MARKET_REGIME"],
      hardInvalidationIds: ["INDUSTRY_THESIS_INVALIDATED", "COMPANY_TRANSMISSION_FAILURE"],
      entryReadinessInputs: ["CYCLE_STAGE", "COMPANY_EXPOSURE", "PRICE_IN_STATE", "REWARD_RISK"],
      intradayRole: "LOW",
      expectedHorizonSessions: [20, 40, 60, 120],
      addActionFamilies: ["ADD_ON_NEW_INFORMATION", "ADD_ON_PULLBACK"],
      reduceActionFamilies: ["CYCLE_PEAK_REDUCE", "THESIS_WEAKENING_REDUCE"],
      exitActionFamilies: ["INDUSTRY_THESIS_EXIT", "COMPANY_THESIS_EXIT"],
    },
    {
      setupId: "TREND_PULLBACK_ENTRY",
      setupVersion: "0.1",
      thesisMechanism: "Industry thesis remains valid while the stock resets within an established structural trend.",
      requiredFamilies: ["INDUSTRY_THESIS"],
      supportiveFamilies: ["TECHNICAL_STRUCTURE", "PRICE_VOLUME", "FUNDAMENTAL_QUALITY", "VALUATION"],
      contextFamilies: ["MARKET_REGIME", "CAPITAL_FLOW"],
      hardInvalidationIds: ["INDUSTRY_THESIS_INVALIDATED", "STRUCTURAL_BREAK_WITH_THESIS_DAMAGE"],
      entryReadinessInputs: ["CYCLE_VALIDITY", "PULLBACK_QUALITY", "REWARD_RISK"],
      intradayRole: "LOW",
      expectedHorizonSessions: [20, 40, 60],
      addActionFamilies: ["ADD_ON_PULLBACK", "ADD_ON_NEW_INFORMATION"],
      reduceActionFamilies: ["CYCLE_PEAK_REDUCE", "PROFIT_PROTECT"],
      exitActionFamilies: ["INDUSTRY_THESIS_EXIT", "STRUCTURE_EXIT"],
    },
    {
      setupId: "SECOND_LEG_BREAKOUT",
      setupVersion: "0.1",
      thesisMechanism: "A still-valid industry cycle produces a second repricing leg after consolidation rather than a late-cycle blow-off.",
      requiredFamilies: ["INDUSTRY_THESIS"],
      supportiveFamilies: ["TECHNICAL_STRUCTURE", "PRICE_VOLUME", "FUNDAMENTAL_QUALITY", "CAPITAL_FLOW"],
      contextFamilies: ["VALUATION", "MARKET_REGIME"],
      hardInvalidationIds: ["CYCLE_PEAK_CONFIRMED", "FAILED_SECOND_LEG", "INDUSTRY_THESIS_INVALIDATED"],
      entryReadinessInputs: ["CYCLE_STAGE", "SECOND_LEG_STRUCTURE", "PV_ACCEPTANCE", "EXTENSION_STATE"],
      intradayRole: "MEDIUM",
      expectedHorizonSessions: [20, 40, 60],
      addActionFamilies: ["ADD_ON_NEW_INFORMATION", "ADD_ON_STRENGTH"],
      reduceActionFamilies: ["CYCLE_PEAK_REDUCE", "CLIMAX_REDUCE"],
      exitActionFamilies: ["INDUSTRY_THESIS_EXIT", "STRUCTURE_EXIT"],
    },
  ],
  allowedRegimes: ["RISK_ON", "TREND", "SECTOR_ROTATION", "RECOVERY", "RANGE", "RISK_OFF"],
  blockedRegimes: [],
  hardInvalidationIds: ["INDUSTRY_THESIS_INVALIDATED", "COMPANY_TRANSMISSION_FAILURE", "CYCLE_PEAK_CONFIRMED"],
  interactionIds: ["INDUSTRY_EARNINGS_TRANSMISSION_CONFLUENCE"],
  versionChangeTriggers: commonVersionTriggers,
  notes: [
    "Industry cycle stage is thesis-primary; chart patterns are timing support only.",
    "Leader-versus-high-beta-beneficiary remains a research comparison, not a permanent leader bonus.",
  ],
});

export const EVENT_DRIVEN_CONTRACT_V0_1 = buildStrategyContract({
  strategyId: "EVENT_DRIVEN",
  strategyVersion: "V0.1-CONTRACT",
  ownerApprovalState: "OWNER_APPROVED",
  thesis:
    "Capture an under- or mis-priced discrete information event only after source timing, transmission mechanism, company exposure, persistence and price-in state are explicit.",
  primaryHorizonSessions: [1, 3, 5, 10, 20, 40],
  evidenceFamilies: [
    {
      family: "EVENT_CATALYST",
      role: "PRIMARY",
      factorIds: ["EVENT.VERIFIED", "EVENT.TRANSMISSION", "EVENT.EXPOSURE", "EVENT.HALF_LIFE", "EVENT.INVALIDATION"],
      dataReadiness: "SEMANTIC_GAP",
      unknownBlocksEligibility: true,
      notes: "Date-level announcements exist; precise firstKnownAt/availableAt and broad canonical news/event semantics remain incomplete.",
    },
    {
      family: "INDUSTRY_THESIS",
      role: "SUPPORTIVE",
      factorIds: ["IND.EVENT_TRANSMISSION"],
      dataReadiness: "SOURCE_EXTENSION_REQUIRED",
      unknownBlocksEligibility: false,
    },
    {
      family: "FUNDAMENTAL_QUALITY",
      role: "SUPPORTIVE",
      factorIds: ["FUND.EVENT_MATERIALITY"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: false,
    },
    {
      family: "PRICE_VOLUME",
      role: "SUPPORTIVE",
      factorIds: ["PV.EVENT_ACCEPTANCE", "PV.EVENT_REJECTION"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: false,
    },
    {
      family: "TECHNICAL_STRUCTURE",
      role: "SUPPORTIVE",
      factorIds: ["TECH.EVENT_REACTION", "TECH.EVENT_PULLBACK"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: false,
    },
    {
      family: "RISK_FRICTION",
      role: "REQUIRED",
      factorIds: ["RISK.TRADABILITY", "RISK.GAP_LIMIT", "RISK.LIQUIDITY"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: true,
    },
  ],
  setups: [
    {
      setupId: "IMMEDIATE_REACTION",
      setupVersion: "0.1",
      thesisMechanism: "Trade only when the event is verified, first-known timing is reliable and immediate execution is genuinely observable/tradable.",
      requiredFamilies: ["EVENT_CATALYST", "RISK_FRICTION"],
      supportiveFamilies: ["PRICE_VOLUME", "TECHNICAL_STRUCTURE"],
      contextFamilies: ["INDUSTRY_THESIS", "FUNDAMENTAL_QUALITY", "MARKET_REGIME"],
      hardInvalidationIds: ["EVENT_DISPROVEN", "TIMING_UNKNOWN", "TRADABILITY_BLOCKED"],
      entryReadinessInputs: ["FIRST_KNOWN_AT", "EVENT_MATERIALITY", "PRICE_ACCEPTANCE", "EXECUTION_FEASIBILITY"],
      intradayRole: "HIGH",
      expectedHorizonSessions: [1, 3, 5],
      addActionFamilies: ["ADD_ON_NEW_INFORMATION", "ADD_ON_STRENGTH"],
      reduceActionFamilies: ["EVENT_DECAY_REDUCE", "PRICE_REJECTION_REDUCE"],
      exitActionFamilies: ["EVENT_INVALIDATION_EXIT", "EXPIRY_EXIT", "STRUCTURE_EXIT"],
    },
    {
      setupId: "EVENT_PULLBACK",
      setupVersion: "0.1",
      thesisMechanism: "A verified event remains active after the first reaction and offers a better risk/reward pullback entry.",
      requiredFamilies: ["EVENT_CATALYST", "RISK_FRICTION"],
      supportiveFamilies: ["PRICE_VOLUME", "TECHNICAL_STRUCTURE", "INDUSTRY_THESIS", "FUNDAMENTAL_QUALITY"],
      contextFamilies: ["MARKET_REGIME"],
      hardInvalidationIds: ["EVENT_DISPROVEN", "EVENT_EXPIRED", "TRANSMISSION_FAILURE"],
      entryReadinessInputs: ["EVENT_HALF_LIFE", "PULLBACK_QUALITY", "PRICE_ACCEPTANCE", "REWARD_RISK"],
      intradayRole: "MEDIUM",
      expectedHorizonSessions: [3, 5, 10, 20],
      addActionFamilies: ["ADD_ON_NEW_INFORMATION", "ADD_ON_PULLBACK"],
      reduceActionFamilies: ["EVENT_DECAY_REDUCE", "PROFIT_PROTECT"],
      exitActionFamilies: ["EVENT_INVALIDATION_EXIT", "EXPIRY_EXIT"],
    },
    {
      setupId: "SECOND_WAVE_ENTRY",
      setupVersion: "0.1",
      thesisMechanism: "Event consequences persist into a second repricing wave after transmission is increasingly validated.",
      requiredFamilies: ["EVENT_CATALYST"],
      supportiveFamilies: ["INDUSTRY_THESIS", "FUNDAMENTAL_QUALITY", "PRICE_VOLUME", "TECHNICAL_STRUCTURE"],
      contextFamilies: ["MARKET_REGIME", "VALUATION"],
      hardInvalidationIds: ["EVENT_EXPIRED", "TRANSMISSION_FAILURE", "COMPANY_EXPOSURE_FALSIFIED"],
      entryReadinessInputs: ["PERSISTENCE", "TRANSMISSION_CONFIRMATION", "SECOND_WAVE_STRUCTURE", "REWARD_RISK"],
      intradayRole: "LOW",
      expectedHorizonSessions: [10, 20, 40],
      addActionFamilies: ["ADD_ON_NEW_INFORMATION", "ADD_ON_STRENGTH"],
      reduceActionFamilies: ["EVENT_DECAY_REDUCE", "THESIS_WEAKENING_REDUCE"],
      exitActionFamilies: ["EVENT_INVALIDATION_EXIT", "EXPIRY_EXIT", "THESIS_TRANSITION_EXIT"],
    },
  ],
  allowedRegimes: ["RISK_ON", "RISK_OFF", "TREND", "RANGE", "HIGH_VOLATILITY", "SECTOR_ROTATION", "PANIC", "RECOVERY"],
  blockedRegimes: [],
  hardInvalidationIds: ["EVENT_DISPROVEN", "EVENT_EXPIRED", "TRANSMISSION_FAILURE", "COMPANY_EXPOSURE_FALSIFIED"],
  interactionIds: ["EVENT_TRANSMISSION_CONFLUENCE"],
  versionChangeTriggers: commonVersionTriggers,
  notes: [
    "Event headline intensity is never sufficient.",
    "Short-lived events must expire; no permanent bonus.",
    "Full Event-Driven Shadow is source-blocked until first-known timing semantics are reliable.",
  ],
});

export const VALUE_REVERSION_CONTRACT_V0_1 = buildStrategyContract({
  strategyId: "VALUE_REVERSION",
  strategyVersion: "V0.1-CONTRACT",
  ownerApprovalState: "RESEARCH_ONLY_APPROVED",
  thesis:
    "Capture valuation repair only when pessimism appears excessive relative to durable fundamentals and a credible repair path emerges with evidence that selling pressure is stabilizing.",
  primaryHorizonSessions: [10, 20, 40, 60, 120],
  evidenceFamilies: [
    {
      family: "VALUATION",
      role: "PRIMARY",
      factorIds: ["VAL.PE", "VAL.PB", "VAL.HISTORICAL_CONTEXT", "VAL.PEER_CONTEXT"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: true,
      notes: "Only current PE/PB are canonical; historical percentiles and richer valuation measures need source/history extension.",
    },
    {
      family: "FUNDAMENTAL_QUALITY",
      role: "PRIMARY",
      factorIds: ["FUND.DURABILITY", "FUND.CASHFLOW", "FUND.BALANCE_SHEET"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: true,
    },
    {
      family: "EVENT_CATALYST",
      role: "PRIMARY",
      factorIds: ["EVENT.REPAIR_CATALYST"],
      dataReadiness: "SEMANTIC_GAP",
      unknownBlocksEligibility: false,
      notes: "A repair path can exist without a discrete event, but a named catalyst must be time/provenance-valid if used.",
    },
    {
      family: "TECHNICAL_STRUCTURE",
      role: "SUPPORTIVE",
      factorIds: ["TECH.STABILIZATION", "TECH.REVERSAL_CONFIRMATION"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: false,
    },
    {
      family: "PRICE_VOLUME",
      role: "SUPPORTIVE",
      factorIds: ["PV.SELLING_EXHAUSTION", "PV.REVERSAL_ACCEPTANCE"],
      dataReadiness: "DERIVABLE_CURRENT",
      unknownBlocksEligibility: false,
    },
    {
      family: "CHIP_OWNERSHIP",
      role: "SUPPORTIVE",
      factorIds: ["CHIP.STABILIZATION"],
      dataReadiness: "PIT_AUDIT_REQUIRED",
      unknownBlocksEligibility: false,
    },
  ],
  setups: [
    {
      setupId: "CAPITULATION_RECOVERY",
      setupVersion: "0.1",
      thesisMechanism: "Valuation is dislocated, durable fundamentals survive and selling pressure transitions from capitulation toward recovery.",
      requiredFamilies: ["VALUATION", "FUNDAMENTAL_QUALITY"],
      supportiveFamilies: ["TECHNICAL_STRUCTURE", "PRICE_VOLUME", "CHIP_OWNERSHIP", "EVENT_CATALYST"],
      contextFamilies: ["INDUSTRY_THESIS", "MARKET_REGIME"],
      hardInvalidationIds: ["STRUCTURAL_DETERIORATION_CONFIRMED", "REPAIR_THESIS_FAILURE"],
      entryReadinessInputs: ["VALUATION_DISLOCATION", "FUNDAMENTAL_DURABILITY", "SELLING_EXHAUSTION", "REVERSAL_CONFIRMATION"],
      intradayRole: "LOW",
      expectedHorizonSessions: [10, 20, 40, 60],
      addActionFamilies: ["ADD_ON_NEW_INFORMATION", "ADD_ON_STRENGTH"],
      reduceActionFamilies: ["REPAIR_WEAKENING_REDUCE", "VALUATION_NORMALIZED_REDUCE"],
      exitActionFamilies: ["VALUE_THESIS_INVALIDATED_EXIT", "STRUCTURE_EXIT"],
    },
    {
      setupId: "FUNDAMENTAL_BOTTOMING",
      setupVersion: "0.1",
      thesisMechanism: "Fundamental deterioration stops worsening while valuation remains depressed and a repair path becomes credible.",
      requiredFamilies: ["VALUATION", "FUNDAMENTAL_QUALITY"],
      supportiveFamilies: ["EVENT_CATALYST", "TECHNICAL_STRUCTURE", "PRICE_VOLUME"],
      contextFamilies: ["INDUSTRY_THESIS", "CHIP_OWNERSHIP", "MARKET_REGIME"],
      hardInvalidationIds: ["FUNDAMENTAL_BOTTOM_FALSIFIED", "BALANCE_SHEET_STRESS_ESCALATION"],
      entryReadinessInputs: ["FUNDAMENTAL_STABILIZATION", "VALUATION_CONTEXT", "REPAIR_PATH", "PRICE_STABILIZATION"],
      intradayRole: "NONE",
      expectedHorizonSessions: [20, 40, 60, 120],
      addActionFamilies: ["ADD_ON_NEW_INFORMATION", "ADD_ON_STRENGTH"],
      reduceActionFamilies: ["REPAIR_WEAKENING_REDUCE"],
      exitActionFamilies: ["VALUE_THESIS_INVALIDATED_EXIT"],
    },
    {
      setupId: "VALUATION_RESET",
      setupVersion: "0.1",
      thesisMechanism: "Price/time correction restores reward-risk while company durability remains intact.",
      requiredFamilies: ["VALUATION", "FUNDAMENTAL_QUALITY"],
      supportiveFamilies: ["TECHNICAL_STRUCTURE", "PRICE_VOLUME", "EVENT_CATALYST"],
      contextFamilies: ["INDUSTRY_THESIS", "MARKET_REGIME"],
      hardInvalidationIds: ["STRUCTURAL_DETERIORATION_CONFIRMED", "REPAIR_THESIS_FAILURE"],
      entryReadinessInputs: ["VALUATION_RESET", "FUNDAMENTAL_DURABILITY", "TIMING_CONFIRMATION", "REWARD_RISK"],
      intradayRole: "LOW",
      expectedHorizonSessions: [20, 40, 60],
      addActionFamilies: ["ADD_ON_NEW_INFORMATION", "ADD_ON_STRENGTH"],
      reduceActionFamilies: ["VALUATION_NORMALIZED_REDUCE", "THESIS_WEAKENING_REDUCE"],
      exitActionFamilies: ["VALUE_THESIS_INVALIDATED_EXIT"],
    },
  ],
  allowedRegimes: ["RISK_ON", "RISK_OFF", "TREND", "RANGE", "PANIC", "RECOVERY", "SECTOR_ROTATION"],
  blockedRegimes: [],
  hardInvalidationIds: ["STRUCTURAL_DETERIORATION_CONFIRMED", "REPAIR_THESIS_FAILURE", "BALANCE_SHEET_STRESS_ESCALATION"],
  interactionIds: ["VALUE_REPAIR_CONFLUENCE"],
  versionChangeTriggers: commonVersionTriggers,
  notes: [
    "Research-only until it beats simple low-valuation and technical-rebound baselines after PIT/OOS/cost controls.",
    "No unconditional averaging down.",
    "Low PE/PB or a large prior price decline alone is never sufficient.",
  ],
});

export const APPROVED_STRATEGY_CONTRACTS_V0_1 = Object.freeze([
  SHORT_MOMENTUM_CONTRACT_V0_1,
  SWING_GROWTH_CONTRACT_V0_1,
  INDUSTRY_TREND_CONTRACT_V0_1,
  EVENT_DRIVEN_CONTRACT_V0_1,
  VALUE_REVERSION_CONTRACT_V0_1,
]);
