export const GLOBAL_REQUIRED_FIREWALLS = Object.freeze(["PIT_GENERATION_LINEAGE","SHADOW_KEYSET_COMPLETENESS","READER_COMPLETENESS","OUTCOME_SESSION_CA_QUALITY","PURGED_FORWARD_HOLDOUT","MARKET_SOURCE_COVERAGE","UNKNOWN_FAIL_CLOSED"]);
export const EXPERIMENT_REQUIRED_FIREWALLS = Object.freeze({
R01:["EQUAL_DATE_ESTIMATOR","BREAKOUT_LABEL_QUALITY"],
R02:["POOL_MATCHED_COMPARATOR","EQUAL_DATE_ESTIMATOR","COHORT_SEMANTIC_INTEGRITY"],
R03:["REGIME_SOURCE_PIT","INDEPENDENT_DATE_COVERAGE"],
R04:["EQUAL_DATE_ESTIMATOR","REDUNDANCY_INCREMENTAL"],
R05:["EQUAL_DATE_ESTIMATOR","NEXT_SESSION_TIMING_QUALITY"],
R06:["REGIME_SOURCE_PIT","TRANSITION_DATE_CONTINUITY"],
R07:["EQUAL_DATE_ESTIMATOR","ATTENTION_PROXY_COVERAGE","REDUNDANCY_INCREMENTAL"],
R08:["PAIRED_EQUAL_DATE_ESTIMATOR","ATTENTION_PROXY_COVERAGE","EXTERNAL_EVIDENCE_GENERATION_ALIGNMENT"],
I01:["EQUAL_DATE_INCREMENTAL_ESTIMATOR","DATE_CLUSTER_ROBUSTNESS","REDUNDANCY_INCREMENTAL"],
I02:["EQUAL_DATE_INCREMENTAL_ESTIMATOR","DATE_CLUSTER_ROBUSTNESS","REDUNDANCY_INCREMENTAL"],
I03:["EQUAL_DATE_INCREMENTAL_ESTIMATOR","DATE_CLUSTER_ROBUSTNESS","REDUNDANCY_INCREMENTAL"],
I04:["EQUAL_DATE_INCREMENTAL_ESTIMATOR","DATE_CLUSTER_ROBUSTNESS","REDUNDANCY_INCREMENTAL"],
I05:["EQUAL_DATE_INCREMENTAL_ESTIMATOR","DATE_CLUSTER_ROBUSTNESS","REDUNDANCY_INCREMENTAL"],
I06:["EQUAL_DATE_INCREMENTAL_ESTIMATOR","DATE_CLUSTER_ROBUSTNESS","REDUNDANCY_INCREMENTAL"],
I07:["EQUAL_DATE_INCREMENTAL_ESTIMATOR","DATE_CLUSTER_ROBUSTNESS","REDUNDANCY_INCREMENTAL"]});
const PASS_STATES=new Set(["PASS","QUALIFIED"]);
export function composeResearchReadiness({experimentId,countReady=false,firewalls={}}={}){
 const specific=EXPERIMENT_REQUIRED_FIREWALLS[experimentId];
 if(!specific)return{experimentId:experimentId??null,countReady:Boolean(countReady),evidenceQualityReady:false,promotionReviewEligible:false,state:"UNKNOWN_EXPERIMENT",required:[],failed:[]};
 const required=[...GLOBAL_REQUIRED_FIREWALLS,...specific];
 const failed=required.filter(name=>!PASS_STATES.has(firewalls?.[name]));
 const evidenceQualityReady=failed.length===0;
 return{experimentId,countReady:Boolean(countReady),evidenceQualityReady,promotionReviewEligible:Boolean(countReady)&&evidenceQualityReady,state:evidenceQualityReady?"EVIDENCE_QUALITY_READY":"EVIDENCE_QUALITY_BLOCKED",required,failed:failed.map(name=>({name,state:firewalls?.[name]??"MISSING"}))};
}
