import assert from "node:assert/strict";
import {classifyMarketYear,validateTwseBoundedYears,validateFullTaiwanPrimary,validateCausalReceipts,validateFoldPlan,classifyModuleReadiness} from "./pattern_first_wave_data_readiness_oracle_v0_1.mjs";
let p=0;const t=(n,f)=>{f();p++;console.log("PASS",n);};
const twseYears=[2018,2019,2020,2021,2022,2023,2024].map(year=>({market:"TWSE",year,dataCoverageState:"PASS",pitReadiness:"PASS_CONSERVATIVE_SESSION_FINALITY",replayReadinessState:"PARTIAL",continuityReadiness:"PARTIAL_UNVERIFIED",technicalPriceReadiness:"PARTIAL_NONPRICE_OBSERVATIONS",symbolSessionReadiness:"PARTIAL_UNKNOWN_GAPS",universeReadiness:"PASS_OFFICIAL_CURRENT_NEWLISTING_DELISTING_UNION",officialDelistingUnionComplete:true}));
t("D8801 accepted raw but partial replay stays partial",()=>assert.equal(classifyMarketYear(twseYears[0]).status,"RAW_PRICE_ACCEPTED_CAUSAL_REPLAY_PARTIAL"));
t("D8802 rejected raw year blocks",()=>assert.equal(classifyMarketYear({dataCoverageState:"PENDING"}).status,"RAW_DATA_NOT_ACCEPTED"));
t("D8803 bounded TWSE raw and universe pass",()=>assert.equal(validateTwseBoundedYears(twseYears).status,"TWSE_BOUNDED_RAW_AND_UNIVERSE_READY"));
t("D8804 missing one TWSE year blocks",()=>assert.equal(validateTwseBoundedYears(twseYears.filter(x=>x.year!==2020)).status,"TWSE_RAW_YEAR_MISSING"));
t("D8805 incomplete universe blocks bounded TWSE",()=>{const a=structuredClone(twseYears);a[2].officialDelistingUnionComplete=false;assert.equal(validateTwseBoundedYears(a).status,"TWSE_UNIVERSE_NOT_READY");});
t("D8806 pending TPEX 2024 blocks full Taiwan",()=>assert.equal(validateFullTaiwanPrimary([...twseYears,{market:"TPEX",year:2024,dataCoverageState:"PENDING"}]).status,"FULL_TAIWAN_BLOCKED_TPEX_2024"));
t("D8807 causal receipt unknown blocks OOS",()=>assert.equal(validateCausalReceipts({membership:true,rawA1:true,symbolSession:false,corporateAction:true,priceLimit:true,disposition:true,observability:true,lineage:true,outcomeAvailability:true,d16Policy:true}).status,"CAUSAL_OOS_BLOCKED"));
t("D8808 all causal receipts pass",()=>assert.equal(validateCausalReceipts({membership:true,rawA1:true,symbolSession:true,corporateAction:true,priceLimit:true,disposition:true,observability:true,lineage:true,outcomeAvailability:true,d16Policy:true}).status,"CAUSAL_OOS_READY"));
t("D8901 frozen fold plan valid",()=>assert.equal(validateFoldPlan({warmupYear:2018,folds:[{train:[2019,2020,2021],test:2022,minPurgeEligibleSessions:20},{train:[2019,2020,2021,2022],test:2023,minPurgeEligibleSessions:20}],finalHoldoutYear:2024,outcomeHorizons:[1,5,20]}).status,"FROZEN_PLAN_VALID"));
t("D8902 holdout drift blocked",()=>assert.equal(validateFoldPlan({warmupYear:2018,folds:[],finalHoldoutYear:2023,outcomeHorizons:[1,5,20]}).status,"FOLD_PLAN_DRIFT"));
t("D8903 horizon search blocked",()=>assert.equal(validateFoldPlan({warmupYear:2018,folds:[{train:[2019,2020,2021],test:2022,minPurgeEligibleSessions:20},{train:[2019,2020,2021,2022],test:2023,minPurgeEligibleSessions:20}],finalHoldoutYear:2024,outcomeHorizons:[1,3,5,20]}).status,"HORIZON_DRIFT"));
t("D9001 first-wave raw feature can remain OOS blocked",()=>assert.equal(classifyModuleReadiness({moduleId:"D01-07",rawFeatureReady:true,causalReceiptsReady:false}).status,"RAW_FEATURE_READY_CAUSAL_OOS_BLOCKED"));
t("D9002 non-first-wave module rejected",()=>assert.equal(classifyModuleReadiness({moduleId:"D01-04",rawFeatureReady:true,causalReceiptsReady:true}).status,"MODULE_OUTSIDE_FIRST_WAVE"));
t("D9003 causal-ready first-wave module eligible",()=>assert.equal(classifyModuleReadiness({moduleId:"D01-09",rawFeatureReady:true,causalReceiptsReady:true}).status,"OOS_EXECUTION_ELIGIBLE"));
console.log(`SUMMARY ${p}/14 PASS`);
