import assert from "node:assert/strict";
import {validateCanonicalR7Payload,validateModuleFeatureSemantics,classifyAliasFamily,validateParentChildPair,validateComparatorFamily,validateLedgerRow,aggregateLedger} from "./pattern_dl098_100_r7_parent_denominator_oracle_v0_1.mjs";
let p=0;const t=(n,f)=>{f();p++;console.log("PASS",n);};
const h="a".repeat(64);
const base={moduleId:"D01-02",predictorFreezeAt:"2021-06-15T14:30:00+08:00",firstObservableAt:"2021-06-15T14:30:00+08:00",requiredSourceBarIds:["b1"],exactSessionHash:h,sourceHistoryHash:h,featureState:"NO_STRUCTURE",featureValues:{signedBodyToRange:.2,bodyToRange:.2,upperWickToRange:.3,lowerWickToRange:.1,closeLocationInRange:.7},aliasLabels:["HAMMER_ALIAS"],contextRefs:[],replaySafe:true,outcomeFieldsPresent:false,informationRoot:"PRICE_OHLC"};

t("D9801 canonical R7 payload passes",()=>assert.equal(validateCanonicalR7Payload(base).status,"R7_CANONICAL_PAYLOAD_VALID"));
t("D9802 outcome contamination fails",()=>assert.equal(validateCanonicalR7Payload({...base,outcomeFieldsPresent:true}).status,"R7_OUTCOME_CONTAMINATED"));
t("D9803 future observable fails",()=>assert.equal(validateCanonicalR7Payload({...base,firstObservableAt:"2021-06-16T00:00:00+08:00"}).status,"R7_LOOKAHEAD"));
t("D9804 D01-02 continuous geometry passes",()=>assert.equal(validateModuleFeatureSemantics(base).status,"MODULE_FEATURE_SEMANTICS_VALID"));
t("D9805 D01-02 named-label root fails",()=>assert.equal(validateModuleFeatureSemantics({...base,informationRoot:"HAMMER"}).status,"D0102_ROOT_INVALID"));
t("D9806 D01-03 ordered geometry must align source bars",()=>assert.equal(validateModuleFeatureSemantics({...base,moduleId:"D01-03",requiredSourceBarIds:["b1","b2"],featureValues:{orderedBarGeometry:[{}]},informationRoot:"PRICE_OHLC"}).status,"D0103_SEQUENCE_GEOMETRY_INCOMPLETE"));
t("D9807 D01-07 backpaint fails",()=>assert.equal(validateModuleFeatureSemantics({...base,moduleId:"D01-07",featureValues:{baseEpisodeId:"base1",widthEligibleSessions:20},retrospectiveBackpaint:true}).status,"D0107_BACKPAINT_PROHIBITED"));
t("D9808 D01-09 requires R5 pass",()=>assert.equal(validateModuleFeatureSemantics({...base,moduleId:"D01-09",r5ContextPass:false,featureValues:{priorEligibleClose:10,currentOpen:11,rawGap:1}}).status,"D0109_R5_CONTEXT_REQUIRED"));
t("D1001 many single-candle aliases dedup to one root",()=>{const x=classifyAliasFamily({moduleId:"D01-02",sourceBarIds:["b1"],aliasLabels:["HAMMER","PIN_BAR","HAMMER"]});assert.equal(x.effectiveIndependentEvidenceCount,1);assert.equal(x.rawAliasCount,2);});
t("D1002 multi-candle aliases over same bars dedup",()=>assert.equal(classifyAliasFamily({moduleId:"D01-03",sourceBarIds:["b1","b2"],aliasLabels:["A","B"]}).effectiveIndependentEvidenceCount,1));
t("D1003 same base episode dedups handles",()=>assert.equal(classifyAliasFamily({moduleId:"D01-07",baseEpisodeId:"BASE-X",aliasLabels:["CUP","ROUND_BASE"]}).redundancyGroup,"BASE-X"));
t("D1004 gap root required",()=>assert.equal(classifyAliasFamily({moduleId:"D01-09",gapRootId:null,aliasLabels:["BREAKAWAY"]}).status,"ALIAS_ROOT_UNKNOWN"));
const pair={moduleId:"D01-02",market:"TWSE",symbol:"1101",targetDate:"2021-06-15",predictorFreezeAt:"p",exactSessionHash:h,sourceHistoryHash:h,foldId:"F1",horizonSetId:"H1-5-20",universeVersion:"U1",blockedRowPolicyId:"B1"};
t("D9901 identical parent child identity passes",()=>assert.equal(validateParentChildPair({...pair,role:"COMMON_PARENT"},{...pair,role:"NAMED_CHILD"}).status,"PARENT_CHILD_COMPARISON_ELIGIBLE"));
t("D9902 different survivor universe fails",()=>assert.equal(validateParentChildPair({...pair,role:"COMMON_PARENT"},{...pair,role:"NAMED_CHILD",universeVersion:"U2"}).status,"PARENT_CHILD_IDENTITY_MISMATCH"));
t("D9903 D01-07 parent family frozen",()=>assert.equal(validateComparatorFamily({moduleId:"D01-07",parentType:"PRIOR_TREND_COMPRESSION_GENERIC_BREAKOUT"}).status,"COMMON_PARENT_VALID"));
t("D9904 wrong parent family fails",()=>assert.equal(validateComparatorFamily({moduleId:"D01-09",parentType:"NAMED_GAP_LABEL"}).status,"COMMON_PARENT_MISMATCH"));
const row={experimentId:"E1",moduleId:"D01-02",universeVersion:"U1",foldId:"F1",predictorDate:"2021-06-15",opportunityId:"O1",state:"NO_STRUCTURE",informationRoot:"PRICE_OHLC",redundancyGroup:"b1"};
t("D1005 complete ledger row passes",()=>assert.equal(validateLedgerRow(row).status,"LEDGER_ROW_VALID"));
t("D1006 blocked row is a legal denominator state",()=>assert.equal(validateLedgerRow({...row,state:"UPSTREAM_DATA_BLOCKED"}).status,"LEDGER_ROW_VALID"));
t("D1007 duplicate opportunity detected instead of double-counted",()=>{const x=aggregateLedger([row,{...row,state:"STRUCTURE_EMITTED"}]);assert.equal(x.status,"DUPLICATE_OPPORTUNITY_DETECTED");assert.equal(x.uniqueOpportunityCount,1);});
t("D1008 no-structure retained in denominator",()=>{const x=aggregateLedger([row,{...row,opportunityId:"O2",state:"STRUCTURE_EMITTED"}]);assert.equal(x.status,"DENOMINATOR_ACCOUNTED");assert.equal(x.counts.NO_STRUCTURE,1);assert.equal(x.counts.STRUCTURE_EMITTED,1);});
console.log(`SUMMARY ${p}/20 PASS`);
