// ALL objects in this file are SYNTHETIC CONTRACT FIXTURES, NOT actual D16 receipts.
import assert from "node:assert/strict";
import {evaluateL3ToL5,summariseModuleDecisions,MODULES} from "./d01_l3_l5_promotion_evidence_oracle_v0_1.mjs";
const src=()=>({
  moduleId:"D01-02",origin:"PHYSICAL_PROSPECTIVE_OR_OOS",
  sourceReceiptHash:"SYN_HASH_FORMAT_ONLY",sourceCommitSha:"SYN_COMMIT_FORMAT_ONLY",
  ownerSignedReceiptId:"SYN_OWNER_FORMAT_ONLY",syntheticFixture:false,
  manifest:{frozenManifestHash:"SYN_MANIFEST_HASH",frozenBeforeOutcomes:true,
    holdoutUntouched:true,horizons:[1,5,20]},
  source:{r1toR7ExactWindowAccepted:true,pitClockCertified:true,
    corporateActionContinuityCertified:true,symbolSessionCoverageComplete:true,
    exchangeLimitAndDispositionCertified:true,rawToContinuityHashCertified:true},
  denominator:{rawObserved:100,sourceBlocked:10,nonSignal:40,
    uniqueEpisodes:45,duplicateSignals:5,missingResultsPreserved:true},
  statistics:{commonParentHash:"SYN_PARENT_HASH",sameSupportHash:"SYN_SUPPORT_HASH",
    experimentLedgerHash:"SYN_EXPERIMENT_HASH",multiplicityReviewed:true,
    resultDisposition:"INCONCLUSIVE"},
  validation:{d16ReceiptId:"SYN_D16_REVIEW",independentReviewerDomain:"D16",
    accepted:true,outcomesActuallyJoined:true,costFieldsPreserved:true,
    noOutcomeTunedParameters:true,mode:"OOS",oos:{trainYears:3,
      testCompleteYearsPerFold:1,holdoutYear:2024,holdoutUntouchedBeforeFreeze:true,
      purgeEmbargoEligibleSessions:20,timeOrderCertified:true},
    l5D16IndependentSignoffId:"SYN_L5_SIGNOFF",robustnessAuditAccepted:true},
  robustness:{independentDateClustersVerified:true,multipleRegimesCertified:true,
    effectStabilityOrRobustNullTested:true,multipleTestingFamilyExhaustive:true,
    negativeControlsPassedOrRefuted:true,sectorAndLiquidityConcentrationReviewed:true,
    survivorshipAndMissingnessSensitiveTested:true},
  redundancy:{sharedPriceRootDeDuplicated:true,fullContextBaselineChecked:true,
    residualIncrementalityConcluded:true},
  cost:{tradingCostSourceCertified:true,commissionsTaxesSpreadSlippageReviewed:true,
    executableFillOrNonfillIncluded:true,costStressSensitivityValidated:true,
    infrastructureNonTradingApplicabilityAcceptedByD16:true}
});
const mutate=(f)=>{const a=src();f(a);return a;};
const cases=[
 ["all 11 modules exactly recognized",()=>assert.equal(MODULES.length,11)],
 ["unrecognized module never eligible",()=>assert.equal(evaluateL3ToL5({...src(),moduleId:"D01-99"}).blockedAt,"MODULE")],
 ["empty evidence retains L3",()=>assert.equal(evaluateL3ToL5({moduleId:"D01-02"}).eligibleLevel,"L3")],
 ["no synthetic fixture can be promoted",()=>assert.equal(evaluateL3ToL5({...src(),syntheticFixture:true}).blockedAt,"PHYSICAL")],
 ["no source receipt hash blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.sourceReceiptHash=null})).blockedAt,"PHYSICAL")],
 ["in-sample alone blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.origin="HISTORICAL_IN_SAMPLE"})).blockedAt,"PHYSICAL")],
 ["no frozen manifest blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.manifest.frozenManifestHash=null})).blockedAt,"PREREG")],
 ["horizon retuning blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.manifest.horizons=[1,5,10]})).blockedAt,"PREREG")],
 ["post-outcome manifest freeze blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.manifest.frozenBeforeOutcomes=false})).blockedAt,"PREREG")],
 ["R5 price-limit missing blocks PIT",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.source.exchangeLimitAndDispositionCertified=false})).blockedAt,"PIT")],
 ["R4 continuity missing blocks PIT",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.source.corporateActionContinuityCertified=false})).blockedAt,"PIT")],
 ["R1-R7 insufficient blocks PIT",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.source.r1toR7ExactWindowAccepted=false})).blockedAt,"PIT")],
 ["denominator attrition mismatch blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.denominator.nonSignal=39})).blockedAt,"DENOMINATOR")],
 ["unknown attrition removed blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.denominator.missingResultsPreserved=false})).blockedAt,"DENOMINATOR")],
 ["same support missing blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.statistics.sameSupportHash=null})).blockedAt,"COMPARATOR")],
 ["multiple testing ignored blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.statistics.multiplicityReviewed=false})).blockedAt,"COMPARATOR")],
 ["unreviewed speculative positive result blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.statistics.resultDisposition="90PCT_WIN"})).blockedAt,"COMPARATOR")],
 ["D16 audit missing blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.independentReviewerDomain="D01"})).blockedAt,"D16")],
 ["no actual joined endpoint blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.outcomesActuallyJoined=false})).blockedAt,"D16")],
 ["no made-up cost fields allowed",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.costFieldsPreserved=false})).blockedAt,"D16")],
 ["future tuning blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.noOutcomeTunedParameters=false})).blockedAt,"D16")],
 ["two-year training cannot pass frozen first wave",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.oos.trainYears=2})).blockedAt,"OOS")],
 ["2018 as holdout cannot substitute 2024",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.oos.holdoutYear=2018})).blockedAt,"OOS")],
 ["no 20-session purge blocked",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.oos.purgeEmbargoEligibleSessions=19})).blockedAt,"OOS")],
 ["prospective 29 observations not enough",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.mode="PROSPECTIVE";x.validation.prospective={completeSamples:29,independentScanDates:15,regimeCount:2,capturedBeforeOutcome:true,completeNoPickPopulation:true}})).blockedAt,"PROSPECTIVE")],
 ["prospective 14 independent dates not enough",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.mode="PROSPECTIVE";x.validation.prospective={completeSamples:30,independentScanDates:14,regimeCount:2,capturedBeforeOutcome:true,completeNoPickPopulation:true}})).blockedAt,"PROSPECTIVE")],
 ["prospective one regime not enough",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.mode="PROSPECTIVE";x.validation.prospective={completeSamples:30,independentScanDates:15,regimeCount:1,capturedBeforeOutcome:true,completeNoPickPopulation:true}})).blockedAt,"PROSPECTIVE")],
 ["prospective valid contract passes conditional L4",()=>{let x=mutate(x=>{x.validation.mode="PROSPECTIVE";x.validation.prospective={completeSamples:30,independentScanDates:15,regimeCount:2,capturedBeforeOutcome:true,completeNoPickPopulation:true};x.robustness.multipleRegimesCertified=false});assert.equal(evaluateL3ToL5(x).eligibleLevel,"L4")}],
 ["OOS complete but robustness incomplete stops at conditional L4",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.robustness.multipleRegimesCertified=false})).blockedAt,"ROBUSTNESS")],
 ["uncontrolled chart root stops at conditional L4",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.redundancy.sharedPriceRootDeDuplicated=false})).blockedAt,"REDUNDANCY")],
 ["cost source missing stops at conditional L4",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.cost.tradingCostSourceCertified=false})).blockedAt,"COST")],
 ["symbol unfilled cases missing stops at conditional L4",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.cost.executableFillOrNonfillIncluded=false})).blockedAt,"COST")],
 ["no independent l5 readback stops conditional L4",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.validation.robustnessAuditAccepted=false})).blockedAt,"L5_REVIEW")],
 ["D01-01 cannot pass without actual operational prospective replay",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.moduleId="D01-01";x.validation.outcomesActuallyJoined=false})).blockedAt,"D16")],
 ["D01-01 legitimate prospective session replay need not claim economic returns",()=>{let x=mutate(x=>{x.moduleId="D01-01";x.validation.outcomesActuallyJoined=false;x.validation.costFieldsPreserved=false;x.validation.operationalProspectiveReplayComplete=true});let r=evaluateL3ToL5(x);assert.equal(r.eligibleLevel,"L5");assert.equal(r.promotionAllowed,false)}],
 ["non-trading D01-01 requires explicit D16 cost exemption",()=>assert.equal(evaluateL3ToL5(mutate(x=>{x.moduleId="D01-01";x.validation.operationalProspectiveReplayComplete=true;x.cost.infrastructureNonTradingApplicabilityAcceptedByD16=false})).blockedAt,"COST")],
 ["hypothetical fully signed test contract reaches L5 candidate state only",()=>{let x=evaluateL3ToL5(src());assert.equal(x.eligibleLevel,"L5");assert.equal(x.reason,"EXTERNAL_PHYSICAL_D16_L5_RECEIPTS_REQUIRE_HUMAN_READBACK_BEFORE_TRACKER_EDIT")}],
 ["hypothetical fully signed fixture NEVER directly edits or authorizes promotion",()=>{let x=evaluateL3ToL5(src());assert.equal(x.promotionAllowed,false);assert.equal(x.reviewReady,true)}],
 ["hypothetical INCONCLUSIVE result does not become positive alpha",()=>assert.equal(evaluateL3ToL5(src()).economicEdge,"INCONCLUSIVE")],
 ["summaries distinguish no readiness",()=>{let x=summariseModuleDecisions(MODULES.map(moduleId=>evaluateL3ToL5({moduleId})));assert.equal(x.L3,11);assert.equal(x.L4,0);assert.equal(x.L5,0)}],
];
let passed=0,failed=[];
for(const [name,fn] of cases){try{fn();passed++;console.log("PASS "+name)}catch(e){failed.push({name,error:e.message});console.error("FAIL "+name+" "+e.message)}}
console.log(JSON.stringify({suite:"D01_11_MODULE_L3_TO_L5_ADMISSION_SYNTHETIC_ONLY",passed,total:cases.length,failed}));
if(failed.length)process.exitCode=1;
