import assert from "node:assert/strict";
import {validateOwnerIdentity,validateEvidenceClock,validateExactWindow,validateSourceHistoryIdentity,validateZeroRows,validateR4ClearNoAction,validateR6Normal,validateCrossReceiptIdentity,validateR7Admission} from "./pattern_dl095_owner_return_acceptance_oracle_v0_1.mjs";

let p=0;
const t=(n,f)=>{f();p++;console.log("PASS",n);};
const hash="a".repeat(64);
const dates=Array.from({length:61},(_,i)=>"S"+String(i+1).padStart(2,"0"));

t("D9501 owner identity valid",()=>assert.equal(validateOwnerIdentity({market:"TWSE",symbol:"1101",targetDate:"2021-06-15",interfaceCutoffAt:"2021-06-15T23:59:59+08:00",outcomeFieldsPresent:false}).status,"OWNER_IDENTITY_VALID"));
t("D9502 wrong target date fails",()=>assert.equal(validateOwnerIdentity({market:"TWSE",symbol:"1101",targetDate:"2021-06-16",interfaceCutoffAt:"2021-06-15T23:59:59+08:00"}).status,"OWNER_RETURN_WITNESS_MISMATCH"));
t("D9503 outcome field contamination fails",()=>assert.equal(validateOwnerIdentity({market:"TWSE",symbol:"1101",targetDate:"2021-06-15",interfaceCutoffAt:"2021-06-15T23:59:59+08:00",outcomeFieldsPresent:true}).status,"OUTCOME_FIELD_CONTAMINATION"));
t("D9504 late evidence fails",()=>assert.equal(validateEvidenceClock({firstObservableAt:"2021-06-16T00:00:00+08:00",interfaceCutoffAt:"2021-06-15T23:59:59+08:00"}).status,"LATE_EVIDENCE_NOT_PIT_ELIGIBLE"));
t("D9505 exact window passes",()=>assert.equal(validateExactWindow({orderedExpectedSessionDates:dates,orderedObservedSessionDates:[...dates],expectedSessionHash:hash,observedSessionHash:hash,unresolvedMissingSessions:0,unresolvedUnexpectedSessions:0}).status,"EXACT_WINDOW_VALID"));
t("D9506 count-only substitution fails",()=>{const o=[...dates];o[0]="S00";assert.equal(validateExactWindow({orderedExpectedSessionDates:dates,orderedObservedSessionDates:o,expectedSessionHash:hash,observedSessionHash:hash,unresolvedMissingSessions:0,unresolvedUnexpectedSessions:0}).status,"EXACT_WINDOW_DATESET_MISMATCH");});
t("D9507 valid source history identity passes",()=>assert.equal(validateSourceHistoryIdentity({rawHistoryAdmissionReceiptId:"RAW-1",sourceHistoryHash:hash,boundSourceHistoryHash:hash}).status,"SOURCE_HISTORY_IDENTITY_VALID"));
t("D9508 mismatched bound source history fails",()=>assert.equal(validateSourceHistoryIdentity({rawHistoryAdmissionReceiptId:"RAW-1",sourceHistoryHash:hash,boundSourceHistoryHash:"b".repeat(64)}).status,"SOURCE_HISTORY_HASH_MISMATCH"));
t("D9509 zero rows without certified empty semantics fail",()=>assert.equal(validateZeroRows({zeroRows:true,requestedRangeMatchesExactly:true,paginationComplete:true,parserComplete:true,emptyRangeSemanticsCertified:false,sourceCoverageComplete:true,sourceHash:"x"}).status,"ZERO_ROWS_UNCERTIFIED_ABSENCE"));
t("D9510 certified zero-row absence passes",()=>assert.equal(validateZeroRows({zeroRows:true,requestedRangeMatchesExactly:true,paginationComplete:true,parserComplete:true,emptyRangeSemanticsCertified:true,sourceCoverageComplete:true,sourceHash:"x"}).status,"ZERO_ROWS_CERTIFIED_ABSENCE"));
t("D9511 R4 no-event without full coverage fails",()=>assert.equal(validateR4ClearNoAction({eventCoverageComplete:true,noEventMayBeClaimed:false,suspensionCoverageComplete:true,symbolSessionCompletenessEvidenceReady:true,revisionCoverageComplete:true,symbolClassification:"NO_EVENT",ambiguityCount:0,continuityReceiptId:"c",receiptHash:"r",sourceHistoryHash:hash}).status,"R4_COMPLETENESS_BLOCKED"));
t("D9512 R4 full clear-no-action eligibility passes",()=>assert.equal(validateR4ClearNoAction({eventCoverageComplete:true,noEventMayBeClaimed:true,suspensionCoverageComplete:true,symbolSessionCompletenessEvidenceReady:true,revisionCoverageComplete:true,symbolClassification:"NO_EVENT",ambiguityCount:0,continuityReceiptId:"c",receiptHash:"r",sourceHistoryHash:hash}).status,"R4_CLEAR_NO_ACTION_ELIGIBLE"));
t("D9513 R6 normal with unresolved changed-trading method fails",()=>assert.equal(validateR6Normal({coverageCompleteForWindow:true,requestedRangeMatchesExactly:true,changedTradingMethodResolved:false,sourceHash:"x",firstObservableAt:"2021-06-15T17:00:00+08:00",state:"CERTIFIED_NORMAL_MATCHING"}).status,"R6_CHANGED_TRADING_METHOD_UNKNOWN"));
t("D9514 R6 certified normal passes",()=>assert.equal(validateR6Normal({coverageCompleteForWindow:true,requestedRangeMatchesExactly:true,changedTradingMethodResolved:true,sourceHash:"x",firstObservableAt:"2021-06-15T17:00:00+08:00",state:"CERTIFIED_NORMAL_MATCHING"}).status,"R6_NORMAL_READY"));
t("D9515 cross-receipt date/hash drift fails",()=>assert.equal(validateCrossReceiptIdentity([{market:"TWSE",symbol:"1101",targetDate:"2021-06-15",interfaceCutoffAt:"c",expectedSessionHash:hash,sourceHistoryHash:hash},{market:"TWSE",symbol:"1101",targetDate:"2021-06-15",interfaceCutoffAt:"c",expectedSessionHash:"b".repeat(64),sourceHistoryHash:hash}]).status,"BUNDLE_CROSS_RECEIPT_IDENTITY_MISMATCH"));
t("D9516 consistent cross-receipt identity passes",()=>assert.equal(validateCrossReceiptIdentity([{market:"TWSE",symbol:"1101",targetDate:"2021-06-15",interfaceCutoffAt:"c",expectedSessionHash:hash,sourceHistoryHash:hash},{market:"TWSE",symbol:"1101",targetDate:"2021-06-15",interfaceCutoffAt:"c",expectedSessionHash:hash,sourceHistoryHash:hash}]).status,"BUNDLE_CROSS_RECEIPT_IDENTITY_VALID"));
t("D9517 R7 blocked if one owner family not pass",()=>assert.equal(validateR7Admission({r1:"PASS",r2:"PASS",r3:"PASS",r4:"PASS",r5:"PASS",r6:"BLOCKED",crossIdentity:"PASS",outcomeFieldsPresent:false}).status,"R7_ADMISSION_BLOCKED"));
t("D9518 R7 ready only with all upstream pass",()=>assert.equal(validateR7Admission({r1:"PASS",r2:"PASS",r3:"PASS",r4:"PASS",r5:"PASS",r6:"PASS",crossIdentity:"PASS",outcomeFieldsPresent:false}).status,"R7_ADMISSION_READY"));

console.log(`SUMMARY ${p}/18 PASS`);
