export function buildResonancePageHtml() {
  return `<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>System 2｜日K共振監控</title>
<style>
:root{color-scheme:dark;--bg:#081018;--panel:#101c28;--line:#23384a;--text:#eef7ff;--muted:#9fb4c8;--green:#3ee6a8;--red:#ff6b7a;--amber:#ffcb66;--blue:#62b6ff}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#122638 0,#081018 55%);color:var(--text);font:15px/1.5 system-ui,-apple-system,"Noto Sans TC",sans-serif}
main{max-width:1200px;margin:auto;padding:24px}.top{display:flex;gap:18px;justify-content:space-between;align-items:flex-end;flex-wrap:wrap}.eyebrow{color:var(--blue);font-weight:700;letter-spacing:.12em}h1{margin:.2rem 0;font-size:clamp(28px,5vw,48px)}.sub{color:var(--muted);max-width:760px}.stats{display:flex;gap:10px;flex-wrap:wrap}.pill{background:#142536;border:1px solid var(--line);border-radius:999px;padding:8px 12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px;margin:24px 0}.card{background:rgba(16,28,40,.94);border:1px solid var(--line);border-radius:16px;padding:16px;cursor:pointer;transition:.18s}.card:hover,.card.active{border-color:var(--blue);transform:translateY(-1px)}.row{display:flex;justify-content:space-between;gap:12px}.symbol{font-size:22px;font-weight:800}.signal{font-weight:800}.buy{color:var(--green)}.exit{color:var(--red)}.forming{color:var(--amber)}.muted{color:var(--muted)}.meter{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:12px 0}.meter i{height:7px;border-radius:6px;background:#26394a}.meter i.on{background:var(--green)}.meter.exit i.on{background:var(--red)}.panel{background:rgba(16,28,40,.96);border:1px solid var(--line);border-radius:18px;padding:18px}.charthead{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}.legend{display:flex;gap:14px;color:var(--muted);font-size:13px}.legend b{color:var(--text)}canvas{width:100%;height:360px;margin-top:12px}.empty{padding:56px 20px;text-align:center;color:var(--muted)}.stamp{font-variant-numeric:tabular-nums;color:var(--muted)}.ops{margin:16px 0;color:var(--muted);font-size:14px}.ops strong{color:var(--amber)}.ops a{color:var(--blue)}@media(max-width:600px){main{padding:16px}canvas{height:300px}}
</style></head><body><main>
<div class="top"><div><div class="eyebrow">SYSTEM 2 · SHADOW MONITOR</div><h1>日K 共振監控</h1><div class="sub">只監控盤後已選定的 bounded pool（最多 9 檔）。EMA16／EMA64／Impulse MACD 全部以日K計算；盤中訊號是暫態，13:30 封棒後仍成立才會確認。</div></div><div class="stats"><span class="pill" id="date">日期 —</span><span class="pill" id="counts">等待資料</span></div></div>
<div class="ops" id="ops" aria-live="polite">正在讀取盤後股池與排程狀態…</div>
<section class="grid" id="cards"></section>
<section class="panel" id="detail"><div class="empty">選擇一檔股票查看日K、EMA 與 Impulse MACD。</div></section>
</main><script>
const state={data:null,selected:null,operations:null};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function card(s){const count=Math.max(s.entryCount||0,s.exitCount||0),isExit=(s.exitCount||0)>(s.entryCount||0);const cls=s.displaySignal==="BUY_RESONANCE"?"buy":s.displaySignal==="EXIT_RESONANCE"?"exit":count?"forming":"muted";const label=s.displaySignal||s.lifecycleState||"WATCH";return '<article class="card '+(state.selected===s.symbol?'active':'')+'" data-s="'+esc(s.symbol)+'"><div class="row"><span class="symbol">'+esc(s.symbol)+'</span><span class="signal '+cls+'">'+esc(label)+'</span></div><div class="meter '+(isExit?'exit':'')+'">'+[1,2,3].map(i=>'<i class="'+(i<=count?'on':'')+'"></i>').join('')+'</div><div class="row muted"><span>'+count+'/3</span><span>'+esc(s.signalConfirmationState||'NONE')+'</span></div></article>'}
function draw(canvas,chart){const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);const rows=chart.candles||[];if(!rows.length)return;const pad={l:48,r:14,t:18,b:38},ph=h*.66-pad.t,ih=h*.25;const vals=rows.flatMap(x=>[x.high,x.low]).filter(Number.isFinite),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;const x=i=>pad.l+(i+.5)*(w-pad.l-pad.r)/rows.length,y=v=>pad.t+(max-v)/span*ph;c.strokeStyle='#23384a';c.lineWidth=1;for(let i=0;i<5;i++){const yy=pad.t+i*ph/4;c.beginPath();c.moveTo(pad.l,yy);c.lineTo(w-pad.r,yy);c.stroke()}const bw=Math.max(2,(w-pad.l-pad.r)/rows.length*.55);rows.forEach((r,i)=>{const up=r.close>=r.open;c.strokeStyle=c.fillStyle=up?'#3ee6a8':'#ff6b7a';c.beginPath();c.moveTo(x(i),y(r.high));c.lineTo(x(i),y(r.low));c.stroke();c.fillRect(x(i)-bw/2,Math.min(y(r.open),y(r.close)),bw,Math.max(1,Math.abs(y(r.open)-y(r.close))))});function line(series,color){c.strokeStyle=color;c.lineWidth=1.6;c.beginPath();let started=false;series.forEach((p,i)=>{if(!Number.isFinite(p.value))return;const xx=x(i),yy=y(p.value);if(!started){c.moveTo(xx,yy);started=true}else c.lineTo(xx,yy)});c.stroke()}line(chart.ema16||[],'#ffcb66');line(chart.ema64||[],'#62b6ff');const hist=(chart.impulseMacd||[]).map(p=>p.histogram).filter(Number.isFinite),m=Math.max(...hist.map(Math.abs),1e-9),base=h-pad.b-ih/2;(chart.impulseMacd||[]).forEach((p,i)=>{if(!Number.isFinite(p.histogram))return;c.fillStyle=p.histogram>=0?'#3ee6a8':'#ff6b7a';const hh=p.histogram/m*(ih*.42);c.fillRect(x(i)-bw/2,base-hh,bw,hh)});c.strokeStyle='#46637a';c.beginPath();c.moveTo(pad.l,base);c.lineTo(w-pad.r,base);c.stroke();(chart.markers||[]).forEach(mk=>{const i=rows.findIndex(r=>r.date===mk.date);if(i<0)return;c.fillStyle=mk.side==='ENTRY'?'#3ee6a8':'#ff6b7a';c.beginPath();c.arc(x(i),y(mk.value),5,0,Math.PI*2);c.fill()})}
function detail(s){const d=document.getElementById('detail');if(!s){d.innerHTML='<div class="empty">目前沒有可顯示的監控資料。</div>';return}d.innerHTML='<div class="charthead"><div><div class="symbol">'+esc(s.symbol)+' · '+esc(s.displaySignal||s.lifecycleState)+'</div><div class="stamp">更新 '+esc(s.updatedAt||s.chart?.asOf||'—')+'｜'+esc(s.finality)+'</div></div><div class="legend"><span><b style="color:#ffcb66">—</b> EMA16</span><span><b style="color:#62b6ff">—</b> EMA64</span><span><b style="color:#3ee6a8">●</b> BUY</span><span><b style="color:#ff6b7a">●</b> EXIT</span></div></div><canvas id="chart"></canvas><div class="muted">Impulse MACD 顯示於下方柱狀區。15分K僅作 execution timing 輔助，不會改寫此日K共振狀態。</div>';requestAnimationFrame(()=>draw(document.getElementById('chart'),s.chart||{}))}
function render(){const d=state.data,rows=d?.symbols||[];const ops=state.operations;const reason={UPSTREAM_CAPACITY_RECEIPT_MISSING:"尚無盤後容量紀錄；等待 System 2 上游完成可驗證選股",POOL_REFRESH_NOT_YET_OBSERVED:"尚未取得 19:00 排程執行紀錄",LATEST_POOL_REFRESH_NO_CAPACITY_RECEIPT:"最近一次 19:00 找不到當日容量紀錄；舊股池已禁止沿用",NO_CURRENT_ELIGIBLE_POOL:"目前沒有可驗證的當日監控股池",ZERO_PICK_ACTIVE:"本次正式為 0 檔；不強行補位",BOUNDED_POOL_READY:"已取得當日有效 bounded pool"};document.getElementById('ops').innerHTML=ops?'<strong>'+esc(reason[ops.state]||ops.state)+'</strong>｜上游 '+esc(ops.upstreamCapacity?.marketDate||'無')+'｜最近 19:00 '+esc(ops.lastPoolRefresh?.asOf||'無')+'｜最近盤中 '+esc(ops.lastIntradayCycle?.asOf||'無')+'｜<a href="/api/system2/resonance/operations" target="_blank" rel="noopener">查看執行診斷</a>':'正在等待執行診斷讀取';document.getElementById('date').textContent='日期 '+(d?.marketDate||'—');document.getElementById('counts').textContent='監控 '+rows.length+'｜暫態 '+(d?.provisionalResonanceCount||0)+'｜確認 '+(d?.confirmedResonanceCount||0);if(!state.selected&&rows[0])state.selected=rows[0].symbol;const cards=document.getElementById('cards');cards.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">目前沒有已選定的監控股池；系統不會為湊數塞入弱股。</div>';cards.querySelectorAll('.card').forEach(el=>el.onclick=()=>{state.selected=el.dataset.s;render()});detail(rows.find(x=>x.symbol===state.selected)||rows[0])}
async function load(){try{const [r,o]=await Promise.all([fetch('/api/system2/resonance',{headers:{accept:'application/json'}}),fetch('/api/system2/resonance/operations',{headers:{accept:'application/json'}}).catch(()=>null)]);if(!r.ok)throw new Error('resonance read failed');state.data=await r.json();state.operations=o?.ok?await o.json():null;render()}catch(e){document.getElementById('counts').textContent='讀取失敗';document.getElementById('detail').innerHTML='<div class="empty">資料暫時無法讀取，請稍後再試。</div>'}}
load();setInterval(load,60000);addEventListener('resize',()=>{const s=state.data?.symbols?.find(x=>x.symbol===state.selected);if(s)detail(s)});
</script></body></html>`;
}
