import assert from 'node:assert/strict';
import {evaluateD16Receipt,evaluateD16ReceiptSet} from '../research/d02_d16_l4_validation_receipt_guard_v0_1.mjs';
let id=0;
const base=(key='D02-02:H001',over={})=>({owner:'D16',receiptId:`R${++id}`,evidenceKey:key,multipleTestingFamilyId:'F1',admissionVersion:'D02_L4_WAVE1_GATE_V0_1_1',experimentVersion:'H001_W1_V0_1',outcomeContractVersion:'D1_V0_1',commonSupportCount:120,independentScanDateCount:35,independentSymbolCount:6,dateDependenceMethod:'DATE_CLUSTER_ROBUST',smallClusterTreatment:'FINITE_SAMPLE_REVIEW',overlapControl:'PURGED_FORWARD_HOLDOUT',purgeResult:'PASS',coverageMissingnessSummary:{unknownShare:0.01},effectTarget:{kind:'MDE',frozenBeforeOutcome:true,version:'MDE_V0_1',unit:'net_bps'},sampleAdequacyStatus:'ADEQUATE',d16MethodFrozen:true,dependenceAssessmentPass:true,effectiveSampleReport:{rowN:120,independentDateN:35},multipleTestingReviewPass:true,concentrationReviewPass:true,costLiquidityReviewPass:true,resultStatus:'VALIDATION_PASS_CANDIDATE',...over});
assert.equal(evaluateD16Receipt(base(),{evidenceKey:'D02-02:H001',experimentVersion:'H001_W1_V0_1'}).promotionReviewEligible,true);
assert.ok(evaluateD16Receipt(base('D02-02:H001',{owner:'D02'}),{evidenceKey:'D02-02:H001'}).reasons.includes('D16_OWNER_REQUIRED'));
assert.ok(evaluateD16Receipt(base(),{evidenceKey:'D02-03:H20'}).reasons.includes('EVIDENCE_KEY_MISMATCH'));
assert.equal(evaluateD16Receipt(base('D02-03:H20'),{evidenceKey:'D02-03:H20'}).pass,true);
let x=base('D02-03:H20',{multipleTestingFamilyId:'F2'});assert.ok(evaluateD16Receipt(x,{evidenceKey:'D02-03:H20'}).reasons.includes('MULTIPLE_TESTING_FAMILY_MISMATCH'));
assert.ok(evaluateD16Receipt(base(),{evidenceKey:'D02-02:H001',experimentVersion:'OTHER'}).reasons.includes('EXPERIMENT_VERSION_MISMATCH'));
assert.ok(evaluateD16Receipt(base('D02-02:H001',{effectTarget:null}),{evidenceKey:'D02-02:H001'}).reasons.includes('EFFECT_OR_PRECISION_TARGET_MISSING'));
assert.ok(evaluateD16Receipt(base('D02-02:H001',{effectTarget:{kind:'MDE',frozenBeforeOutcome:false,version:'V',unit:'bps'}}),{evidenceKey:'D02-02:H001'}).reasons.includes('EFFECT_TARGET_NOT_FROZEN_BEFORE_OUTCOME'));
assert.ok(evaluateD16Receipt(base('D02-02:H001',{independentScanDateCount:0}),{evidenceKey:'D02-02:H001'}).reasons.includes('INDEPENDENT_DATE_COUNT_INVALID'));
assert.ok(evaluateD16Receipt(base('D02-02:H001',{dateDependenceMethod:''}),{evidenceKey:'D02-02:H001'}).reasons.includes('DATE_DEPENDENCE_METHOD_MISSING'));
assert.ok(evaluateD16Receipt(base('D02-02:H001',{overlapControl:''}),{evidenceKey:'D02-02:H001'}).reasons.includes('OVERLAP_CONTROL_MISSING'));
assert.equal(evaluateD16Receipt(base('D02-02:H001',{sampleAdequacyStatus:'INSUFFICIENT',resultStatus:'INSUFFICIENT_EVIDENCE'}),{evidenceKey:'D02-02:H001'}).promotionReviewEligible,false);
assert.ok(evaluateD16Receipt(base('D02-02:H001',{effectiveSampleReport:null}),{evidenceKey:'D02-02:H001'}).reasons.includes('EFFECTIVE_SAMPLE_REPORT_MISSING'));
assert.ok(evaluateD16Receipt(base('D02-02:H001',{multipleTestingReviewPass:false}),{evidenceKey:'D02-02:H001'}).reasons.includes('MULTIPLE_TESTING_REVIEW_NOT_PASS'));
assert.ok(evaluateD16Receipt(base('D02-02:H001',{concentrationReviewPass:false}),{evidenceKey:'D02-02:H001'}).reasons.includes('CONCENTRATION_REVIEW_NOT_PASS'));
assert.ok(evaluateD16Receipt(base('D02-02:H001',{costLiquidityReviewPass:false}),{evidenceKey:'D02-02:H001'}).reasons.includes('COST_LIQUIDITY_REVIEW_NOT_PASS'));
const sem=base('D02-01:SEMANTIC_GOVERNANCE',{multipleTestingFamilyId:'F0',admissionVersion:'D02_01_L4_SEMANTIC_ADMISSION_V0_1',experimentVersion:'D02_01_SEM_V0_1',effectTarget:{kind:'SEMANTIC_MATERIALITY_TARGET',frozenBeforeOutcome:true,version:'SMT_V0_1',unit:'classification_delta_share'},costLiquidityReviewPass:false,resultStatus:'SEMANTIC_GOVERNANCE_CANDIDATE'});assert.equal(evaluateD16Receipt(sem,{evidenceKey:'D02-01:SEMANTIC_GOVERNANCE'}).promotionReviewEligible,true);
assert.ok(evaluateD16Receipt({...sem,resultStatus:'VALIDATION_PASS_CANDIDATE'},{evidenceKey:'D02-01:SEMANTIC_GOVERNANCE'}).reasons.includes('SEMANTIC_MODULE_WRONG_CANDIDATE_STATUS'));
const p=base('D02-09:PIVOT_SIGNED_VOLUME',{multipleTestingFamilyId:'F3',admissionVersion:'D02_L4_WAVE2_ADMISSION_V0_1'});assert.equal(evaluateD16Receipt(p,{evidenceKey:'D02-09:PIVOT_SIGNED_VOLUME'}).pass,true);
assert.ok(evaluateD16Receipt(p,{evidenceKey:'D02-09:PARTICIPATION_TRAJECTORY'}).reasons.includes('EVIDENCE_KEY_MISMATCH'));
const prof=base('D02-12:PRICE_BY_VOLUME_PROFILE',{multipleTestingFamilyId:'F5',admissionVersion:'D02_L4_WAVE2_ADMISSION_V0_1'});assert.equal(evaluateD16Receipt(prof,{evidenceKey:'D02-12:PRICE_BY_VOLUME_PROFILE'}).pass,true);
assert.ok(evaluateD16Receipt(prof,{evidenceKey:'D02-12:TIME_OF_DAY_VOLUME_CURVE'}).reasons.includes('EVIDENCE_KEY_MISMATCH'));
const neg=base('D02-07:SVB20',{multipleTestingFamilyId:'F3',admissionVersion:'D02_L4_WAVE2_ADMISSION_V0_1',sampleAdequacyStatus:'ADEQUATE',resultStatus:'NO_INCREMENTAL_VALUE'});assert.equal(evaluateD16Receipt(neg,{evidenceKey:'D02-07:SVB20'}).pass,true);assert.equal(evaluateD16Receipt(neg,{evidenceKey:'D02-07:SVB20'}).promotionReviewEligible,false);
let a=base();let set=evaluateD16ReceiptSet([a,{...a}]);assert.equal(set.fatalIntegrity,true);assert.ok(set.duplicateReceiptIds.includes(a.receiptId));
a=base();set=evaluateD16ReceiptSet([a,{...a,evidenceKey:'D02-03:H20'}]);assert.equal(set.fatalIntegrity,true);assert.ok(set.crossEvidenceKeyReceiptReuse.includes(a.receiptId));
set=evaluateD16ReceiptSet([base(),base('D02-03:H20')]);assert.equal(set.crossModuleSampleBorrowingAllowed,false);assert.equal(set.maturityPromotionAuthorized,false);assert.equal(set.formalCoreChangeAuthorized,false);
console.log(JSON.stringify({status:'PASS',tests:24,contract:'D02_D16_L4_RECEIPT_GUARD_V0_1'}));