import assert from 'node:assert/strict';
import {evaluatePVE241Receipt,evaluatePVE241Dataset} from '../research/d02_pve241_prospective_receipt_guard_v0_1.mjs';
const d='2026-11-03'; let n=0; const iso=t=>d+'T'+t+'+08:00';
const base=(o={})=>({scanDate:d,eventId:'PVE241:'+d+':'+n++,evidenceKey:'D02-02:H001',moduleId:'D02-02',symbol:'2330',exchange:'TWSE',session:'REGULAR',sourceProvider:'FUGLE',sourceEndpoint:'historical/candles',sourceRole:'PROSPECTIVE_CAPTURE',sourceCapturedProspectively:true,sourceAvailableAt:iso('10:15:01'),sourceRetrievedAt:iso('10:15:02'),featureFirstKnownAt:iso('10:15:03'),decisionCutoffAt:iso('10:16:00'),decisionTimeObservableClaim:true,timeframe:'MINUTE',timezone:'Asia/Taipei',barCompleted:true,rawVolumeUnit:'LOTS',rawVolumeValue:12,normalizedVolumeUnit:'SHARES',normalizedVolumeValue:12000,volumeNormalizationFactor:1000,crossTimeframeJoin:false,unitNormalizationPass:true,corporateActionClass:'NONE',corporateActionFlagKnown:true,adjustedPriceClaim:false,priceAdjustmentMode:'RAW_UNADJUSTED',mechanicalReferencePriceControlPass:true,priceGapTreatedAsOrdinaryDiscovery:false,unitScaleBridgeVerified:false,resetCleanBaselinePass:false,comparableParticipationUsed:false,supplyDenominatorNormalized:false,priceInformationRoot:'PRICE_OHLC',volumeInformationRoot:'VOLUME_TURNOVER',priceDerivedIndependentVote:false,residualIncrementalityRequired:true,commonSupportRequired:true,proxyClass:'DIRECT_VOLUME',intentIdentified:false,independentIntentSourcePresent:false,trueOfiEligible:false,completeVolumeIdentityClaim:false,openingAuctionCompletenessClaim:false,motiveLabel:'',admissionClassification:'ELIGIBLE',...o});
let t=0; const test=(fn)=>{fn();t++;};
test(()=>assert.equal(evaluatePVE241Receipt(base()).pass,true));
test(()=>assert.equal(evaluatePVE241Receipt(base()).promotionEligible,true));
test(()=>assert.ok(evaluatePVE241Receipt(base({rawVolumeUnit:'SHARES'})).reasons.includes('MINUTE_REGULAR_LOT_UNIT_MUST_BE_LOTS')));
test(()=>assert.ok(evaluatePVE241Receipt(base({volumeNormalizationFactor:1})).reasons.includes('LOTS_NORMALIZATION_FACTOR_MUST_BE_1000')));
test(()=>assert.ok(evaluatePVE241Receipt(base({normalizedVolumeValue:12})).reasons.includes('NORMALIZED_VOLUME_VALUE_MISMATCH')));
test(()=>assert.equal(evaluatePVE241Receipt(base({timeframe:'DAILY',rawVolumeUnit:'SHARES',rawVolumeValue:12000,normalizedVolumeValue:12000,volumeNormalizationFactor:1})).pass,true));
test(()=>assert.ok(evaluatePVE241Receipt(base({crossTimeframeJoin:true,unitNormalizationPass:false})).reasons.includes('CROSS_TIMEFRAME_JOIN_REQUIRES_UNIT_NORMALIZATION')));
test(()=>assert.ok(evaluatePVE241Receipt(base({sourceAvailableAt:iso('10:15:04')})).reasons.includes('SOURCE_AVAILABLE_AFTER_FEATURE_FIRST_KNOWN')));
test(()=>assert.ok(evaluatePVE241Receipt(base({sourceRetrievedAt:iso('10:15:04')})).reasons.includes('SOURCE_RETRIEVED_AFTER_FEATURE_FIRST_KNOWN')));
test(()=>assert.ok(evaluatePVE241Receipt(base({featureFirstKnownAt:iso('10:16:01')})).reasons.includes('FEATURE_KNOWN_AFTER_DECISION_CUTOFF')));
test(()=>{const r=evaluatePVE241Receipt(base({sourceRole:'HISTORICAL_REPLAY_ONLY',sourceCapturedProspectively:false,sourceRetrievedAt:iso('16:31:00'),featureFirstKnownAt:iso('16:31:01'),decisionCutoffAt:iso('18:10:00'),decisionTimeObservableClaim:false}));assert.equal(r.pass,true);assert.equal(r.promotionEligible,false);});
test(()=>assert.ok(evaluatePVE241Receipt(base({sourceRole:'HISTORICAL_REPLAY_ONLY',sourceCapturedProspectively:false,sourceRetrievedAt:iso('16:31:00'),featureFirstKnownAt:iso('16:31:01'),decisionCutoffAt:iso('18:10:00'),decisionTimeObservableClaim:true})).reasons.includes('HISTORICAL_REPLAY_CANNOT_PROVE_DECISION_TIME_OBSERVABILITY')));
test(()=>assert.ok(evaluatePVE241Receipt(base({adjustedPriceClaim:true})).reasons.includes('MINUTE_ADJUSTED_PRICE_CLAIM_FORBIDDEN')));
test(()=>assert.ok(evaluatePVE241Receipt(base({corporateActionClass:'UNKNOWN'})).reasons.includes('UNKNOWN_CORPORATE_ACTION_CANNOT_BE_ELIGIBLE')));
test(()=>assert.ok(evaluatePVE241Receipt(base({corporateActionClass:'EX_RIGHT_DIVIDEND',mechanicalReferencePriceControlPass:false})).reasons.includes('EX_RIGHT_DIVIDEND_REFERENCE_PRICE_CONTROL_REQUIRED')));
test(()=>assert.ok(evaluatePVE241Receipt(base({corporateActionClass:'EX_RIGHT_DIVIDEND',priceGapTreatedAsOrdinaryDiscovery:true})).reasons.includes('CORPORATE_ACTION_GAP_CANNOT_BE_ORDINARY_PRICE_DISCOVERY')));
test(()=>assert.ok(evaluatePVE241Receipt(base({corporateActionClass:'UNIT_SCALE'})).reasons.includes('UNIT_SCALE_CONTINUITY_NOT_PROVEN')));
test(()=>assert.equal(evaluatePVE241Receipt(base({corporateActionClass:'UNIT_SCALE',unitScaleBridgeVerified:true})).pass,true));
test(()=>assert.ok(evaluatePVE241Receipt(base({corporateActionClass:'SUPPLY_CHANGE',comparableParticipationUsed:true})).reasons.includes('SUPPLY_CHANGE_COMPARABILITY_NOT_PROVEN')));
test(()=>assert.ok(evaluatePVE241Receipt(base({priceInformationRoot:'PRICE_RETURN'})).reasons.includes('PRICE_INFORMATION_ROOT_MISMATCH')));
test(()=>assert.ok(evaluatePVE241Receipt(base({volumeInformationRoot:'PRICE_OHLC'})).reasons.includes('VOLUME_INFORMATION_ROOT_MISMATCH')));
test(()=>assert.ok(evaluatePVE241Receipt(base({priceDerivedIndependentVote:true})).reasons.includes('PRICE_DERIVED_SECOND_VOTE_FORBIDDEN')));
test(()=>assert.ok(evaluatePVE241Receipt(base({residualIncrementalityRequired:false})).reasons.includes('RESIDUAL_INCREMENTALITY_REQUIRED')));
test(()=>assert.ok(evaluatePVE241Receipt(base({commonSupportRequired:false})).reasons.includes('COMMON_SUPPORT_REQUIRED')));
test(()=>assert.ok(evaluatePVE241Receipt(base({proxyClass:'BID_ASK_SIDE_VOLUME',trueOfiEligible:true})).reasons.includes('TRUE_OFI_MUST_REMAIN_FALSE_FOR_PROXY')));
test(()=>assert.ok(evaluatePVE241Receipt(base({proxyClass:'BID_ASK_SIDE_VOLUME',completeVolumeIdentityClaim:true})).reasons.includes('PROXY_CANNOT_CLAIM_COMPLETE_VOLUME_IDENTITY')));
test(()=>assert.ok(evaluatePVE241Receipt(base({proxyClass:'BID_ASK_SIDE_VOLUME',openingAuctionCompletenessClaim:true})).reasons.includes('OPENING_AUCTION_COMPLETENESS_CLAIM_FORBIDDEN')));
test(()=>assert.ok(evaluatePVE241Receipt(base({proxyClass:'PROVIDER_TRADE_PRESSURE',intentIdentified:true})).reasons.includes('INTENT_REQUIRES_INDEPENDENT_SOURCE')));
test(()=>assert.ok(evaluatePVE241Receipt(base({proxyClass:'PROVIDER_TRADE_PRESSURE',motiveLabel:'ACCUMULATION'})).reasons.includes('FORBIDDEN_MOTIVE_OVERCLAIM')));
test(()=>assert.equal(evaluatePVE241Receipt(base({intentIdentified:true,independentIntentSourcePresent:true,independentIntentSourceKnownAt:iso('10:15:00')})).pass,true));
test(()=>assert.ok(evaluatePVE241Receipt(base({intentIdentified:true,independentIntentSourcePresent:true,independentIntentSourceKnownAt:iso('10:17:00')})).reasons.includes('INDEPENDENT_INTENT_SOURCE_AFTER_DECISION_CUTOFF')));
test(()=>{const a=base();const r=evaluatePVE241Dataset([a,{...a}]);assert.equal(r.fatalIntegrity,true);assert.ok(r.datasetReasons.includes('DUPLICATE_EVENT_ID_SAME_DATE'));});
test(()=>{const r=evaluatePVE241Dataset([base(),base({timeframe:'DAILY',rawVolumeUnit:'SHARES',rawVolumeValue:5000,normalizedVolumeValue:5000,volumeNormalizationFactor:1,sourceEndpoint:'historical/candles-daily'})]);assert.equal(r.receiptSchemaReady,true);assert.equal(r.promotionEligibleReceiptCount,2);assert.equal(r.maturityPromotionAuthorized,false);assert.equal(r.outcomeAccessAuthorized,false);assert.equal(r.numericalTargetAuthorized,false);assert.equal(r.d16MethodSelectionAuthorized,false);assert.equal(r.formalCoreChangeAuthorized,false);});
console.log(JSON.stringify({status:'PASS',tests:t,contract:'D02_PVE241_PROSPECTIVE_RECEIPT_GUARD_V0_1'}));
