import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {buildFactorRegistry,extendFactorRegistry,freezeFactorExperiment,diagnoseSignals,buildShadowDiagnostic,digest,d03Registry} from '../research/system1_sda_shadow_v0_1.mjs';
import {EMPTY_LEDGER_HEAD,definitionHash,appendExperimentEvent,replayExperimentLedger} from '../research/experiment_holdout_guard_v0_1.mjs';
const at='2026-10-05T08:00:00Z',later='2026-10-05T09:00:00Z';
const reg=(factorId,moduleId='D03-02',extra={})=>({factorId,factorVersion:'1',moduleId,experimentVersion:'E1',parameters:{horizon:20},...extra});
const regs=[reg('ret20'),...['roc20','momentum20','log20','negativeRet','percentileRet'].map(id=>reg(id,'D03-02',{aliasOf:['ret20','1']})),reg('EMA16','D03-01'),reg('EMA64','D03-01'),reg('MACD','D03-08'),reg('MTF','D03-13')];
const generic=(id,root,domain='D01')=>reg(id,null,{lineage:{...d03Registry.modules[0],factorId:id,domainId:domain,informationRoot:root,sourceFamily:root,independenceStatus:'RESIDUAL_CANDIDATE'}});
regs.push(generic('breakout',['PRICE_OHLC']),generic('priceVolume',['PRICE_OHLC','VOLUME_TURNOVER'],'D02'),generic('accounting',['FUNDAMENTAL_ACCOUNTING'],'D08'),reg('outcome','D03-04'),reg('missing',null));
const registry=buildFactorRegistry(regs);
assert.deepEqual(extendFactorRegistry(registry,registry.registryDigest,[regs[0]]),registry);
assert.throws(()=>extendFactorRegistry(registry,'f'.repeat(64),[]),/HEAD_MISMATCH/);
assert.throws(()=>extendFactorRegistry(registry,registry.registryDigest,[{...regs[0],parameters:{horizon:5}}]),/CONFLICT/);
const frozen=freezeFactorExperiment(registry,[['ret20','1'],['roc20','1']],{});
assert.equal(frozen.parameterFamilyId,'PF_D03_RETURN_5_20_60');
assert.equal(frozen.factorRegistryDigest,registry.registryDigest);
assert.throws(()=>freezeFactorExperiment(registry,[['ret20','1']],{parameterFamilyId:'RESET'}),/RESET_FORBIDDEN/);
assert.throws(()=>freezeFactorExperiment(registry,[['ret20','1'],['MACD','1']],{}),/CROSS_FAMILY/);
const signal=(factorId,extra={})=>({factorId,factorVersion:'1',active:true,firstObservableAt:at,...extra});
const diag=ids=>diagnoseSignals(ids.map(x=>typeof x==='string'?signal(x):x),registry,later);
assert.equal(diag(['ret20','roc20','momentum20','log20']).dedupedShadowScore,1);
assert.equal(diag(['ret20','negativeRet','percentileRet']).dedupedShadowScore,1);
assert.equal(diag(['EMA16','EMA64','MACD','breakout','MTF']).dedupedShadowScore,1);
assert.equal(diag(['ret20','priceVolume']).dedupedShadowScore,1);
assert.equal(diag(['ret20','accounting']).dedupedShadowScore,2);
assert.equal(diag(['ret20','accounting']).effectiveIndependentEvidenceCount,0);
assert.equal(diag(['ret20','ret20']).dedupedShadowScore,1);
assert.equal(diag(['missing']).dedupedShadowScore,0);
assert.equal(diag(['missing']).status,'INCOMPLETE');
assert.equal(diag(['outcome']).invalid[0].reason,'OUTCOME_NOT_A_VOTE');
assert.equal(diag([signal('ret20',{firstObservableAt:'2026-10-06T00:00:00Z'})]).status,'INCOMPLETE');
assert.equal(diag([signal('ret20',{active:0})]).status,'INCOMPLETE');
assert.equal(diag([signal('ret20',{active:false})]).rawScore,0);
assert.deepEqual(buildFactorRegistry([...regs,regs[0]]),registry);
assert.throws(()=>buildFactorRegistry([...regs,{...regs[0],parameters:{horizon:10}}]),/CONFLICT/);
assert.throws(()=>buildFactorRegistry([regs[0],reg('alias','D03-02',{aliasOf:['ret20','1'],parameters:{horizon:60}})]),/DRIFT/);
assert.throws(()=>buildFactorRegistry([reg('bad','D03-99')]),/UNKNOWN_D03/);
const tampered=structuredClone(registry);tampered.entries[0].lineage.informationRoot=['EVENT_DISCLOSURE'];
assert.throws(()=>diagnoseSignals([signal('ret20')],tampered,later),/INTEGRITY/);
const {registryDigest:_,...body}=tampered;tampered.registryDigest=digest(body);
assert.throws(()=>diagnoseSignals([signal('ret20')],tampered,later),/MAPPING_DRIFT/);
const candidates=Array.from({length:5},(_,i)=>({symbol:String(i),officialClose:100,formalEligible:true,signals:(i===4?['accounting','ret20']:['ret20','roc20','log20']).map(x=>signal(x))}));
candidates.push({symbol:'1000',officialClose:1000,formalEligible:true,signals:[signal('ret20')]});
const input={generationId:'fixture-generation',decisionAt:later,sourceReceiptDigest:'a'.repeat(64),registry,candidates,formalSelectedSymbols:['0','1','2','1000']};
const before=structuredClone(input),output=buildShadowDiagnostic(input);
assert.deepEqual(input,before);assert.deepEqual(output.rawVoteShadowTop6,['0','1','2','1000']);assert.deepEqual(output.dedupShadowTop6,['4','0','1','1000']);
assert.equal(output.formalVsDedupTop6Overlap,3);assert.deepEqual(output,buildShadowDiagnostic(input));
const missing=structuredClone(input);missing.candidates[0].signals.push(signal('missing'));
assert.equal(buildShadowDiagnostic(missing).dedupShadowTop6,null);
assert.throws(()=>buildShadowDiagnostic({...input,candidates:[...candidates,candidates[0]]}),/DUPLICATE_SYMBOL/);
assert.equal(output.formalOptimizationCandidate,'NONE');assert.equal(output.economicSuperiority,'UNKNOWN');
const spec={factorRegistryDigest:registry.registryDigest,targetId:'T',target:{return:'D5'},benchmarkId:'B',benchmark:{kind:'price-only'},holdoutId:'H1',holdoutDatasetHash:'a'.repeat(64),parameterFamilyId:'PF_D03_RETURN_5_20_60',factorVersion:'ret20-v1',primaryOutcomeHorizon:'D5',multiplicityMethod:'D16_REVIEW_PENDING_NO_PROMOTION',stopRule:'SINGLE_FROZEN_READ',minimumDetectableEffect:'NOT_ESTIMATED_NO_PROMOTION',frozenCandidateSet:frozen.frozenCandidateSet,inspectionPolicy:'SINGLE_INSPECTION_THEN_DEVELOPMENT'};
spec.targetHash=definitionHash(spec.target);spec.benchmarkHash=definitionHash(spec.benchmark);
let events=[],head=EMPTY_LEDGER_HEAD;
const event=(type,extra={},id='E1')=>({eventId:`event-${events.length}`,at,action:{type,experimentId:id,experimentVersion:'1',...extra}});
const append=(type,extra={},id='E1')=>{const result=appendExperimentEvent(events,head,event(type,extra,id));events.push(result.event);head=result.state.head;return result.state;};
append('REGISTER',{spec});
assert.throws(()=>appendExperimentEvent(events,head,event('REGISTER',{spec:{...spec,stopRule:'PEEK'}})),/IMMUTABLE/);
assert.throws(()=>appendExperimentEvent(events,head,event('REGISTER',{spec:{...spec,target:{return:'D20'}}},'E2')),/HASH_MISMATCH/);
let state=append('INSPECT',{inspectionId:'look1'});assert.equal(state.holdouts[0].holdoutUseCount,1);assert.equal(state.holdouts[0].consumedAsDevelopmentData,false);
state=append('LOCK_OUTCOME',{result:'NEGATIVE',outcomeDigest:'b'.repeat(64)});assert.equal(state.experiments[0].outcomeLock.result,'NEGATIVE');
assert.throws(()=>appendExperimentEvent(events,head,event('LOCK_OUTCOME',{result:'POSITIVE',outcomeDigest:'c'.repeat(64)})),/ALREADY_LOCKED/);
state=append('INSPECT',{inspectionId:'look2'});assert.equal(state.holdouts[0].consumedAsDevelopmentData,true);assert.equal(state.holdouts[0].firstInspectedAt,at);
state=append('REGISTER',{spec:{...spec,holdoutId:'cosmetic-new-name'}},'E2');assert.equal(state.experiments[1].consumedAsDevelopmentData,true);assert.equal(state.familyTrials[spec.parameterFamilyId],2);
assert.throws(()=>appendExperimentEvent(events,head,event('REGISTER',{spec:{...spec,holdoutDatasetHash:'d'.repeat(64)}},'E3')),/DATASET_MUTATION/);
assert.throws(()=>appendExperimentEvent(events,head,event('LOCK_OUTCOME',{result:'POSITIVE',outcomeDigest:'b'.repeat(64)},'E2')),/OUTCOME_RECEIPT_REQUIRED/);
assert.throws(()=>appendExperimentEvent(events,head,event('REGISTER',{spec:{...spec,holdoutId:'cosmetic-new-name',holdoutDatasetHash:'e'.repeat(64)}},'E3')),/DATASET_MUTATION/);
assert.throws(()=>replayExperimentLedger(events.slice(0,-1),head),/HEAD_MISMATCH/);
const corrupt=structuredClone(events);corrupt[0].action.spec.stopRule='MUTATED';assert.throws(()=>replayExperimentLedger(corrupt,head),/INTEGRITY/);
assert.throws(()=>appendExperimentEvent(events,EMPTY_LEDGER_HEAD,event('INSPECT',{inspectionId:'stale'})),/HEAD_MISMATCH/);
assert.throws(()=>appendExperimentEvent(events,head,{...event('INSPECT',{inspectionId:'backdate'}),at:'2026-10-04T00:00:00Z'}),/MONOTONIC/);
assert.equal(state.experiments.every(x=>x.promotionAuthorized===false),true);
const dir=mkdtempSync(join(tmpdir(),'sda-class-a-'));
try {
  const inputFile=join(dir,'input.json'),outFile=join(dir,'receipt.json'),ledger=join(dir,'ledger.ndjson');
  writeFileSync(inputFile,JSON.stringify(input));
  const cli=(args)=>{const result=spawnSync(process.execPath,['tests/run_system1_sda_shadow_v0_1.mjs',...args],{encoding:'utf8'});if(result.error) throw result.error;return result;};
  assert.equal(cli(['diagnose',inputFile,outFile]).status,0);assert.deepEqual(JSON.parse(readFileSync(outFile)),output);assert.notEqual(cli(['diagnose',inputFile,outFile]).status,0);
  writeFileSync(inputFile,JSON.stringify({eventId:'register',at,action:{type:'REGISTER',experimentId:'CLI',experimentVersion:'1',spec}}));
  const first=cli(['ledger-append',inputFile,ledger,EMPTY_LEDGER_HEAD]);assert.equal(first.status,0,first.stderr);
  const state=JSON.parse(first.stdout),raw=readFileSync(ledger,'utf8');
  assert.notEqual(cli(['ledger-append',inputFile,ledger,EMPTY_LEDGER_HEAD]).status,0);assert.equal(readFileSync(ledger,'utf8'),raw);
  writeFileSync(ledger+'.lock','');assert.notEqual(cli(['ledger-append',inputFile,ledger,state.head]).status,0);assert.equal(readFileSync(ledger,'utf8'),raw);
} finally {rmSync(dir,{recursive:true,force:true});}
console.log(JSON.stringify({status:'PASS',tickets:['SDA-001','SDA-004','SDA-016'],fixtureOnly:true,formalCoreImpact:false,providerCallDelta:0,economicSuperiority:'UNKNOWN'}));
