import assert from 'node:assert/strict';
import {evaluateWave2Row,evaluateWave2Outcome,evaluateWave2Dataset} from '../research/d02_l4_wave2_admission_evaluator_v0_1.mjs';
const d='2026-11-03';
const iso=t=>`${d}T${t}+08:00`;
let n=0;
const base=(moduleId,over={})=>({moduleId,scanDate:d,eventId:`${moduleId}:${d}:${n++}`,gate0to6Pass:true,dataQaPass:true,cleanCohortProvenance:true,generationAligned:true,formalIsolationPass:true,sourceContinuityPass:true,commonSupportPass:true,cleanScanDate:true,featureFirstKnownAt:iso('10:30:01'),decisionCutoffAt:iso('10:31:00'),outcomeStartAt:iso('10:45:00'),outcomeKnownAt:iso('13:31:00'),outcomeStatus:'COMPLETED',...over});
const d04=(o={})=>base('D02-04',{state:'LOW_PARTICIPATION_CANDIDATE',candidateLabelImmutable:true,priceConsolidationGeometryKnown:true,volatilityContractionKnown:true,liquidityContextKnown:true,laterDemandStateUsedInFeature:false,...o});
const d05=(o={})=>base('D02-05',{participationBand:'EXTREME',volumeBandFrozenPreOutcome:true,priceResponseStateKnown:true,volatilityContextKnown:true,eventContextKnown:true,liquidityContextKnown:true,motiveLabel:'UNKNOWN',...o});
const d07=(o={})=>base('D02-07',{signedVolumeBalance20:0.1,dailyVolumeContinuityPass:true,pricePathControlPresent:true,directVolumeControlPresent:true,responsePersistenceControlPresent:true,identicalSupportCvsD:true,rawObvIndependentVote:false,unfrozenObvSlopeUsed:false,...o});
const d08=(o={})=>base('D02-08',{providerTradePressureProxy:0.2,classificationCoverage:0.8,unclassifiedVolume:20,pressureSourceContinuityPass:true,spreadDepthLiquidityControlsKnown:true,trueOfiEligible:false,dynamicAbsorptionEligible:false,participantIntentEligible:false,motiveLabel:'UNKNOWN',...o});
const d09p=(o={})=>base('D02-09',{family:'PIVOT_SIGNED_VOLUME',genericDivergenceBooleanUsed:false,visualPivotSelectionUsed:false,allPairScanUsed:false,bestWindowSearchUsed:false,underlyingPriceAndVolumeTrajectoriesPresent:true,confirmedPivotChronologyPass:true,sameTypeSameScaleConsecutivePivots:true,priceContinuityPass:true,dailyVolumeContinuityPass:true,laterPivotConfirmedAt:iso('10:20:00'),...o});
const d09t=(o={})=>base('D02-09',{family:'PARTICIPATION_TRAJECTORY',genericDivergenceBooleanUsed:false,visualPivotSelectionUsed:false,allPairScanUsed:false,bestWindowSearchUsed:false,underlyingPriceAndVolumeTrajectoriesPresent:true,trajectoryClockPass:true,...o});
const d10=(o={})=>base('D02-10',{trendParentOwner:'D03',directTrendPresent:true,directParticipationPresent:true,explicitInteractionTransformPresent:true,identicalSupportCvsD:true,noTripleVote:true,trendParentKnownAt:'2026-11-02T13:31:00+08:00',volumeBarEnd:iso('10:30:00'),volumeSourceFetchedAt:iso('10:30:00'),interactionFirstKnownAt:iso('10:30:01'),slotKey:'10:15',interactionUsesCumvolPace:true,...o});
const d11=(role='ADMITTED',o={})=>base('D02-11',{cohortRole:role,rejectionReason:'BELOW_MIN_LOTS',reasonStratified:true,executionCostEvidenceKnown:true,spreadDepthEvidenceKnown:true,thresholdVersionFrozen:true,thresholdSweepUsed:false,...o});
const d12t=(o={})=>base('D02-12',{family:'TIME_OF_DAY_VOLUME_CURVE',sameSlotRvolControlPresent:true,cumulativePaceControlPresent:true,priceLocationControlPresent:true,slotKey:'12:45',fullSessionCompletenessClaim:false,...o});
const d12p=(o={})=>base('D02-12',{family:'PRICE_BY_VOLUME_PROFILE',sameSlotRvolControlPresent:true,cumulativePaceControlPresent:true,priceLocationControlPresent:true,prospectiveCapture:true,historicalBackfillUsed:false,closingAuctionCompletenessClaim:false,closingAuctionCoverageProven:false,...o});

for(const row of [d04(),d05(),d07(),d08(),d09p(),d09t(),d10(),d11(),d11('LIQUIDITY_REJECTED_CONTROL'),d12t(),d12p()]) assert.equal(evaluateWave2Row(row).pass,true);
assert.ok(evaluateWave2Row(d04({laterDemandStateUsedInFeature:true})).reasons.includes('D02_04_HINDSIGHT_DEMAND_REEXPANSION_LEAK'));
assert.ok(evaluateWave2Row(d05({motiveLabel:'DISTRIBUTION'})).reasons.includes('D02_05_FORBIDDEN_MOTIVE_LABEL'));
assert.ok(evaluateWave2Row(d07({rawObvIndependentVote:true})).reasons.includes('D02_07_RAW_OBV_DOUBLE_COUNT'));
assert.ok(evaluateWave2Row(d08({trueOfiEligible:true})).reasons.includes('D02_08_TRUE_OFI_MUST_REMAIN_FALSE'));
assert.ok(evaluateWave2Row(d08({classificationCoverage:1.1})).reasons.includes('D02_08_CLASSIFICATION_COVERAGE_INVALID'));
assert.ok(evaluateWave2Row(d09p({laterPivotConfirmedAt:iso('10:31:00')})).reasons.includes('D02_09_PIVOT_CONFIRMED_AFTER_FEATURE_CLOCK'));
assert.ok(evaluateWave2Row(d09p({genericDivergenceBooleanUsed:true})).reasons.includes('D02_09_GENERIC_BOOLEAN_FORBIDDEN'));
assert.ok(evaluateWave2Row(d10({interactionFirstKnownAt:iso('10:29:59')})).reasons.includes('D02_10_INTERACTION_KNOWN_TOO_EARLY'));
assert.ok(evaluateWave2Row(d10({slotKey:'09:00',interactionUsesCumvolPace:true})).reasons.includes('D02_10_09_00_CUMPACE_STRUCTURAL_REDUNDANCY'));
assert.ok(evaluateWave2Row(d11('LIQUIDITY_REJECTED_CONTROL',{thresholdSweepUsed:true})).reasons.includes('D02_11_THRESHOLD_SWEEP_FORBIDDEN'));
assert.ok(evaluateWave2Row(d12t({slotKey:'13:15'})).reasons.includes('D02_12_TIME_CURVE_OUTSIDE_09_00_13_00'));
assert.ok(evaluateWave2Row(d12p({historicalBackfillUsed:true})).reasons.includes('D02_12_HISTORICAL_PROFILE_BACKFILL_FORBIDDEN'));
assert.ok(evaluateWave2Row(d12p({closingAuctionCompletenessClaim:true})).reasons.includes('D02_12_CLOSING_AUCTION_CLAIM_UNPROVEN'));
assert.ok(evaluateWave2Row(d04({featureFirstKnownAt:iso('10:32:00')})).reasons.includes('FEATURE_KNOWN_AFTER_DECISION_CUTOFF'));
assert.ok(evaluateWave2Outcome(d05({outcomeStatus:'CENSORED'})).reasons.includes('OUTCOME_CENSORED_OR_UNKNOWN'));
assert.ok(evaluateWave2Outcome(d05({outcomeStartAt:iso('10:30:01')})).reasons.includes('OUTCOME_NOT_STRICTLY_FUTURE'));
let a=d07();let r=evaluateWave2Dataset([a,{...a}]);assert.equal(r.fatalIntegrity,true);assert.ok(r.datasetReasons.includes('DUPLICATE_EVENT_ID_SAME_DATE'));
a=d07();r=evaluateWave2Dataset([a,{...a,scanDate:'2026-11-04'}]);assert.equal(r.fatalIntegrity,true);assert.ok(r.datasetReasons.includes('DUPLICATE_EVENT_ID_CROSS_DATE'));
r=evaluateWave2Dataset([d11('ADMITTED')]);assert.equal(r.byModule['D02-11'].sourceAdmissionReady,false);assert.equal(r.byModule['D02-11'].blocker,'D02_11_REASON_STRATIFIED_REJECTED_CONTROL_INCOMPLETE');
r=evaluateWave2Dataset([d11('ADMITTED'),d11('LIQUIDITY_REJECTED_CONTROL')]);assert.equal(r.byModule['D02-11'].counterfactualLaneReady,true);
r=evaluateWave2Dataset([d09p(),d09t(),d12t(),d12p()]);assert.deepEqual(r.byModule['D02-09'].families,['PIVOT_SIGNED_VOLUME','PARTICIPATION_TRAJECTORY']);assert.deepEqual(r.byModule['D02-12'].families,['TIME_OF_DAY_VOLUME_CURVE','PRICE_BY_VOLUME_PROFILE']);
r=evaluateWave2Dataset([d04(),d05(),d07(),d08(),d09p(),d10(),d11('ADMITTED'),d11('LIQUIDITY_REJECTED_CONTROL'),d12t()]);assert.equal(r.maturityPromotionAuthorized,false);assert.equal(r.l4SampleAdequacyAuthorized,false);assert.equal(r.formalCoreChangeAuthorized,false);
console.log(JSON.stringify({status:'PASS',tests:32,contract:'D02_L4_WAVE2_ADMISSION_V0_1'}));
