import assert from 'node:assert/strict';
import {evaluatePVE242LaneBridge} from '../research/d02_pve242_lane_bridge_guard_v0_1.mjs';
const d='2026-11-03';const iso=t=>d+'T'+t+'+08:00';
const rec=(o={})=>({schemaVersion:'D02_PROSPECTIVE_PV_PROVENANCE_RECEIPT_V0_1',researchOnly:true,outcomeBlind:true,symbol:'2330',marketDate:d,timeframe:'15m',source:{provider:'X',endpoint:'live',retrievedAt:iso('10:30:01'),sourceTier:'LIVE_PROVIDER',rawPayloadHash:'abcdef1234567890'},availability:{availableAt:iso('10:30:00'),firstKnownAt:iso('10:30:02'),decisionCutoff:iso('10:31:00'),knownByDecisionCutoff:true},bar:{barStart:iso('10:15:00'),barEnd:iso('10:30:00'),timezone:'Asia/Taipei',completed:true},volume:{rawValue:12,rawUnit:'LOTS',normalizedValue:12000,normalizedUnit:'SHARES',conversionRule:'REGULAR_LOT_X_1000',unitContinuityStatus:'PASS'},price:{adjustmentSemantics:'UNADJUSTED',corporateActionContaminated:false},corporateAction:{status:'NONE_VERIFIED',receiptRef:null,knownByDecisionCutoff:true},informationRoot:'PRICE_PLUS_VOLUME_DERIVED',participation:{proxyClass:'RVOL',intentIdentified:false,openingAuctionCompleteness:'NOT_APPLICABLE'},admission:{pitPass:true,unitPass:true,corporateActionPass:true,sourcePass:true,intentFirewallPass:true,eligibleForProspectiveEvidence:true,reasons:[]},...o});
let n=0;const T=f=>{f();n++;};
const h001={sameSlotBaselineClean:true,slotHistoryCount:20,currentSlotCoverageValid:true,commonSupportPass:true};
T(()=>assert.equal(evaluatePVE242LaneBridge(rec(),'D02-02:H001',h001).pass,true));
T(()=>assert.ok(evaluatePVE242LaneBridge(rec({timeframe:'1d',volume:{rawValue:12000,rawUnit:'SHARES',normalizedValue:12000,normalizedUnit:'SHARES',conversionRule:'IDENTITY_SHARES',unitContinuityStatus:'PASS'}}),'D02-02:H001',h001).reasons.includes('H001_REQUIRES_15M_RECEIPT')));
T(()=>assert.ok(evaluatePVE242LaneBridge(rec({bar:{...rec().bar,barStart:iso('10:00:00'),barEnd:iso('10:15:00')},availability:{...rec().availability,availableAt:iso('10:15:00'),firstKnownAt:iso('10:15:02'),decisionCutoff:iso('10:16:00')},source:{...rec().source,retrievedAt:iso('10:15:01')}}),'D02-02:H001',h001).reasons.includes('H001_SLOT_BEFORE_10_15_OR_INVALID')));
T(()=>assert.ok(evaluatePVE242LaneBridge(rec(),'D02-02:H001',{...h001,slotHistoryCount:19}).reasons.includes('H001_SLOT_HISTORY_LT_20')));
const h20={primitiveEventOwner:'D01-05',primitiveEventId:'E1',comparatorPrimitiveEventId:'E1',anchorBarStart:iso('10:15:00'),comparatorAnchorBarStart:iso('10:15:00'),outcomeHorizon:'B2',comparatorOutcomeHorizon:'B2'};
T(()=>assert.equal(evaluatePVE242LaneBridge(rec(),'D02-03:H20',h20).pass,true));
T(()=>assert.ok(evaluatePVE242LaneBridge(rec({timeframe:'1d',volume:{rawValue:12000,rawUnit:'SHARES',normalizedValue:12000,normalizedUnit:'SHARES',conversionRule:'IDENTITY_SHARES',unitContinuityStatus:'PASS'}}),'D02-03:H20',h20).reasons.includes('H20_REQUIRES_15M_RECEIPT')));
T(()=>assert.ok(evaluatePVE242LaneBridge(rec(),'D02-03:H20',{...h20,primitiveEventOwner:'D02'}).reasons.includes('H20_PRIMITIVE_OWNER_INVALID')));
T(()=>assert.ok(evaluatePVE242LaneBridge(rec(),'D02-03:H20',{...h20,comparatorPrimitiveEventId:'E2'}).reasons.includes('H20_PRIMITIVE_EVENT_ID_MISMATCH')));
const h003={sameFeatureBarForPAndPV:true,h003HypothesisCleanEvent:true,preEventOnlyExpiry:false};
T(()=>assert.equal(evaluatePVE242LaneBridge(rec(),'D02-06:H003',h003).pass,true));
T(()=>assert.ok(evaluatePVE242LaneBridge(rec({timeframe:'1d',volume:{rawValue:12000,rawUnit:'SHARES',normalizedValue:12000,normalizedUnit:'SHARES',conversionRule:'IDENTITY_SHARES',unitContinuityStatus:'PASS'}}),'D02-06:H003',h003).reasons.includes('H003_REQUIRES_15M_RECEIPT')));
T(()=>assert.ok(evaluatePVE242LaneBridge(rec(),'D02-06:H003',{...h003,sameFeatureBarForPAndPV:false}).reasons.includes('H003_P_PV_FEATURE_BAR_MISMATCH')));
const pRec=rec({participation:{proxyClass:'BID_ASK_SIDE_VOLUME',intentIdentified:false,openingAuctionCompleteness:'INCOMPLETE_BY_SOURCE_CONTRACT'}});
const pctx={pressureSourceContinuityPass:true,classificationCoverage:0.8,trueOfiEligible:false,participantIntentEligible:false,dynamicAbsorptionEligible:false};
T(()=>assert.equal(evaluatePVE242LaneBridge(pRec,'D02-08',pctx).pass,true));
T(()=>assert.ok(evaluatePVE242LaneBridge(rec({timeframe:'1d',volume:{rawValue:12000,rawUnit:'SHARES',normalizedValue:12000,normalizedUnit:'SHARES',conversionRule:'IDENTITY_SHARES',unitContinuityStatus:'PASS'},participation:{proxyClass:'TOTAL_VOLUME',intentIdentified:false,openingAuctionCompleteness:'NOT_APPLICABLE'}}),'D02-08',pctx).reasons.includes('D02_08_REQUIRES_INTRADAY_RECEIPT')));
T(()=>assert.ok(evaluatePVE242LaneBridge(rec(),'D02-08',pctx).reasons.includes('D02_08_PROXY_CLASS_NOT_PRESSURE_CAPABLE')));
T(()=>assert.ok(evaluatePVE242LaneBridge(pRec,'D02-08',{...pctx,trueOfiEligible:true}).reasons.includes('D02_08_TRUE_OFI_MUST_REMAIN_FALSE')));
T(()=>assert.equal(evaluatePVE242LaneBridge(rec(),'GENERIC_PROVENANCE',{}).pass,true));
T(()=>{const r=evaluatePVE242LaneBridge(rec(),'GENERIC_PROVENANCE',{});assert.equal(r.cleanSelectionDateAuthorized,false);assert.equal(r.outcomeAccessAuthorized,false);assert.equal(r.maturityPromotionAuthorized,false);assert.equal(r.formalCoreChangeAuthorized,false);});
console.log(JSON.stringify({status:'PASS',tests:n,contract:'D02_PVE242_LANE_BRIDGE_GUARD_V0_1'}));
