import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const load=p=>JSON.parse(readFileSync(new URL(p,import.meta.url),"utf8"));
const receipt=load("../evidence/S2_CORR003_P01_P05_PRODUCER_RECEIPT_RECONCILIATION_20261009_V0_1.json");
const system1=load("../../research/SYSTEM1_ISSUE1024_P01_P02_P04_REAL_GITHUB_D1_PRODUCER_EVIDENCE_20261009_V0_1.json");
const data=load("../evidence/S2_ISSUE1026_P03_P05_ACCOUNT_GRAPHQL_NONAUTHORIZING_REAL_RUN_20261009_V0_1.json");
const inventory=load("../evidence/S2_CORR003_P01_P05_PHYSICAL_EVIDENCE_GAP_INVENTORY_20261009_V0_1.json");
const audit=load("../evidence/S2_CORR003_INDEPENDENT_PHYSICAL_CLOSURE_GATE_20261009_V0_1.json");
const policy=load("../evidence/S2_CORR_20261007_003_SYSTEM1_AFTER_MARKET_RESERVE_POLICY_V0_1.json");
const queue=load("../SYSTEM2_CORRECTION_QUEUE.json");
assert.equal(receipt.directiveId,"S2-CORR-20261007-003");
assert.equal(receipt.lane,"REMEDIATION_LANE");
assert.equal(receipt.artifactType,"IMMUTABLE_READONLY_INTAKE_CROSS_PRODUCER_NO_PHYSICAL_PROMOTION");
assert.equal(receipt.sourceReceipts.length,2);
assert.deepEqual(receipt.sourceReceipts.map(x=>x.issue),[1024,1026]);
assert.deepEqual(receipt.sourceReceipts.map(x=>x.scope),[["P01","P02","P04"],["P03","P05"]]);
assert.equal(receipt.originalCriteriaMapped,19);
assert.equal(queue.directives.find(x=>x.directiveId===receipt.directiveId).acceptanceCriteria.length,19);
assert.equal(receipt.supportingEvidence.checksDocumented,inventory.supportChecksDocumentedTotal);
assert.equal(receipt.supportingEvidence.checksTotal,inventory.supportChecksTotal);
assert.equal(receipt.system1.healthyDatesObserved,system1.sourceCoverage.healthyDatesCount);
assert.deepEqual(receipt.system1.healthyAfterMarketCronRows.map(x=>x.cronRowId),system1.directRealCronRows.map(x=>x.cronRowId));
assert.deepEqual(receipt.system1.accountWholeV7DbDailyUsage.map(x=>x.rowsRead),system1.accountUsageObservations.slice(0,2).map(x=>x.V7_DB.rowsRead));
assert.ok(receipt.system1.healthyAfterMarketCronRows.every(x=>x.exactBusinessPersistenceReadbackVerified===false));
assert.ok(receipt.system1.accountWholeV7DbDailyUsage.every(x=>!x.per2335CostKnown && !x.physicalBusinessReadbackSameGeneration));
assert.equal(receipt.system1.afterMarketOct07Failure,"FAILED");
assert.equal(receipt.system1.oct08FollowupC1,"FAILURE");
assert.equal(receipt.system1.laterHealthyPersistenceReadback,false);
assert.equal(receipt.system1.nextNaturalEligibleTradingDate,"2026-10-12");
assert.equal(receipt.data.physicalAccountObservation.runId,data.realAccountObservation.runId);
assert.equal(receipt.data.physicalAccountObservation.jobId,data.realAccountObservation.jobId);
assert.equal(receipt.data.physicalAccountObservation.artifactDigest,data.realAccountObservation.artifactDigest);
assert.equal(receipt.data.physicalAccountObservation.rowsReadLowerBound,data.realAccountObservation.rowsReadLowerBound);
assert.equal(receipt.data.physicalAccountObservation.rowsWrittenLowerBound,data.realAccountObservation.rowsWrittenLowerBound);
assert.equal(receipt.data.physicalAccountObservation.analyticsLagGuarantee,"NOT_DOCUMENTED_BY_VENDOR");
assert.equal(receipt.data.physicalAccountObservation.readHeadroomProven,false);
assert.equal(receipt.data.physicalAccountObservation.writeHeadroomProven,false);
assert.ok(receipt.data.priorObservedAccountLowerBounds.rowsReadLowerBound < receipt.data.physicalAccountObservation.rowsReadLowerBound);
assert.equal(receipt.data.usageDifferencesMustNotBeWriterAttributed,true);
assert.equal(receipt.data.d1SqlQueries,0);
assert.equal(receipt.data.d1Writes,0);
assert.equal(receipt.data.hotD1ScoutCompleted,0);
assert.equal(receipt.data.hotD1FullCensusCompleted,0);
assert.equal(receipt.data.physicalMissingKeys,"UNKNOWN");
assert.equal(receipt.data.actualPostFixMultiwriterGrantResultProven,false);
assert.ok(["P01","P02","P03","P04","P05"].every(k=>receipt.gateStatus[k]===false));
assert.equal(receipt.gateStatus.independentlyQualified,0);
assert.ok(audit.prerequisiteGates.every(x=>x.state==="PENDING"&&!x.evidenceQualified));
assert.equal(inventory.qualifiedPhysicalGateCount,0);
assert.equal(policy.reserveNumberAuthorized,false);
assert.equal(policy.authorizedReserveRows,null);
assert.equal(policy.readReserveNumberAuthorized,false);
assert.equal(policy.authorizedReadReserveRows,null);
assert.equal(queue.directives.find(x=>x.directiveId===receipt.directiveId).status,"VERIFYING");
assert.ok(Object.values(receipt.protected).every(Boolean));
console.log("CORR003_PRODUCER_RECEIPT_RECONCILIATION_PASS sourceProvenance=2 support=15/38 physical=0/5 noD1Sql=true");
