import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const workflow=await readFile(new URL("../../.github/workflows/system2-2026-twse-oct09-one-shot.yml",import.meta.url),"utf8");
const writer=await readFile(new URL("../scripts/historical_current_year_segment_backfill_v0_1.mjs",import.meta.url),"utf8");
const preflight=await readFile(new URL("../scripts/historical_segment_schema_readonly_preflight_v0_1.mjs",import.meta.url),"utf8");
assert.match(workflow,/^on:\s*\n\s+push:\s*\n/m);
assert.match(workflow,/branches:\s*\[main\]/);
assert.match(workflow,/system2-2026-twse-oct09-one-shot\.yml/);
assert.doesNotMatch(workflow,/^\s*schedule:/m);
assert.doesNotMatch(workflow,/workflow_dispatch:/);
assert.match(workflow,/group:\s*system2-isolated-d1-writer/);
assert.match(workflow,/cancel-in-progress:\s*false/);
assert.match(workflow,/github\.event_name == 'push'/);
assert.match(workflow,/p\.year!==2026\|\|p\.month!==10\|\|p\.day!==9\|\|p\.hour<8/);
assert.match(workflow,/SYSTEM2_HISTORY_SEGMENT_MARKET:\s*TWSE/);
assert.doesNotMatch(workflow,/SYSTEM2_HISTORY_SEGMENT_MARKET:\s*TPEX/);
assert.match(workflow,/historical_segment_schema_readonly_preflight_v0_1\.mjs/);
assert.match(workflow,/historical_current_year_segment_backfill_v0_1\.mjs/);
assert.match(workflow,/if: always\(\)/);
assert.match(workflow,/upload-artifact@v4/);
assert.match(workflow,/permissions:\s*\n\s+contents: read/);
assert.doesNotMatch(workflow,/wrangler\s+deploy|provision_system2_d1|CREATE_SYSTEM2_ISOLATED_D1|SYSTEM2_CAPTURE_ENABLED:\s*true/);
assert.match(preflight,/verifySystem2SegmentSchemaReadonlyV0_1/);
assert.match(writer,/readHistoricalSegmentReceiptV0_1/);
assert.match(writer,/finalizeHistoricalSegmentCheckpointFromReceiptV0_1/);
assert.match(writer,/fetchHistoricalTwseMonthlyTradingDatesV0_1/);
assert.match(writer,/BLOCKED_FAIL_CLOSED_SEGMENT_BACKFILL/);
assert.match(writer,/observedAtFactory:/);
assert.match(writer,/throughMonth=currentMonth-1/);
console.log("System2 2026 TWSE Oct09 single-writer post-reset one-shot guard PASS");
