const base=process.env.V7_BASE_URL||'https://fugle-test.imihan0630.workers.dev';
const token=process.env.V7_ADMIN_TOKEN;
if(!token) throw new Error('Missing V7_ADMIN_TOKEN');
const res=await fetch(base+'/api/push-test',{method:'POST',headers:{'x-admin-token':token,'content-type':'application/json'}});
const txt=await res.text();
console.log(txt);
if(!res.ok) throw new Error('push-test HTTP '+res.status+': '+txt);
const data=JSON.parse(txt);
if(data?.ok!==true || data?.result?.sent!==true) throw new Error('push-test not accepted: '+txt);
console.log('V7 push-test webhook accepted. receiptVerified='+String(data?.result?.receiptVerified));
